// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: shipping/service/v1/shipping_error.proto

package servicev1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShippingServiceErrorReason int32

const (
	ShippingServiceErrorReason_UNKNOWN_ERROR ShippingServiceErrorReason = 0
)

// Enum value maps for ShippingServiceErrorReason.
var (
	ShippingServiceErrorReason_name = map[int32]string{
		0: "UNKNOWN_ERROR",
	}
	ShippingServiceErrorReason_value = map[string]int32{
		"UNKNOWN_ERROR": 0,
	}
)

func (x ShippingServiceErrorReason) Enum() *ShippingServiceErrorReason {
	p := new(ShippingServiceErrorReason)
	*p = x
	return p
}

func (x ShippingServiceErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShippingServiceErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_shipping_service_v1_shipping_error_proto_enumTypes[0].Descriptor()
}

func (ShippingServiceErrorReason) Type() protoreflect.EnumType {
	return &file_shipping_service_v1_shipping_error_proto_enumTypes[0]
}

func (x ShippingServiceErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShippingServiceErrorReason.Descriptor instead.
func (ShippingServiceErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_shipping_service_v1_shipping_error_proto_rawDescGZIP(), []int{0}
}

var File_shipping_service_v1_shipping_error_proto protoreflect.FileDescriptor

const file_shipping_service_v1_shipping_error_proto_rawDesc = "" +
	"\n" +
	"(shipping/service/v1/shipping_error.proto\x12\x13shipping.service.v1\x1a\x13errors/errors.proto*5\n" +
	"\x1aShippingServiceErrorReason\x12\x11\n" +
	"\rUNKNOWN_ERROR\x10\x00\x1a\x04\xa0E\xf4\x03B\xe0\x01\n" +
	"\x17com.shipping.service.v1B\x12ShippingErrorProtoP\x01ZCtlgitea.com/pingtai/gopkg/api/_gen/go/shipping/service/v1;servicev1\xa2\x02\x03SSX\xaa\x02\x13Shipping.Service.V1\xca\x02\x13Shipping\\Service\\V1\xe2\x02\x1fShipping\\Service\\V1\\GPBMetadata\xea\x02\x15Shipping::Service::V1b\x06proto3"

var (
	file_shipping_service_v1_shipping_error_proto_rawDescOnce sync.Once
	file_shipping_service_v1_shipping_error_proto_rawDescData []byte
)

func file_shipping_service_v1_shipping_error_proto_rawDescGZIP() []byte {
	file_shipping_service_v1_shipping_error_proto_rawDescOnce.Do(func() {
		file_shipping_service_v1_shipping_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shipping_service_v1_shipping_error_proto_rawDesc), len(file_shipping_service_v1_shipping_error_proto_rawDesc)))
	})
	return file_shipping_service_v1_shipping_error_proto_rawDescData
}

var file_shipping_service_v1_shipping_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shipping_service_v1_shipping_error_proto_goTypes = []any{
	(ShippingServiceErrorReason)(0), // 0: shipping.service.v1.ShippingServiceErrorReason
}
var file_shipping_service_v1_shipping_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shipping_service_v1_shipping_error_proto_init() }
func file_shipping_service_v1_shipping_error_proto_init() {
	if File_shipping_service_v1_shipping_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shipping_service_v1_shipping_error_proto_rawDesc), len(file_shipping_service_v1_shipping_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shipping_service_v1_shipping_error_proto_goTypes,
		DependencyIndexes: file_shipping_service_v1_shipping_error_proto_depIdxs,
		EnumInfos:         file_shipping_service_v1_shipping_error_proto_enumTypes,
	}.Build()
	File_shipping_service_v1_shipping_error_proto = out.File
	file_shipping_service_v1_shipping_error_proto_goTypes = nil
	file_shipping_service_v1_shipping_error_proto_depIdxs = nil
}
