// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: shipping/service/v1/shipping.proto

package servicev1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShipOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipOrderReq) Reset() {
	*x = ShipOrderReq{}
	mi := &file_shipping_service_v1_shipping_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipOrderReq) ProtoMessage() {}

func (x *ShipOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_service_v1_shipping_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipOrderReq.ProtoReflect.Descriptor instead.
func (*ShipOrderReq) Descriptor() ([]byte, []int) {
	return file_shipping_service_v1_shipping_proto_rawDescGZIP(), []int{0}
}

func (x *ShipOrderReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ShipOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipOrderReply) Reset() {
	*x = ShipOrderReply{}
	mi := &file_shipping_service_v1_shipping_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipOrderReply) ProtoMessage() {}

func (x *ShipOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_service_v1_shipping_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipOrderReply.ProtoReflect.Descriptor instead.
func (*ShipOrderReply) Descriptor() ([]byte, []int) {
	return file_shipping_service_v1_shipping_proto_rawDescGZIP(), []int{1}
}

func (x *ShipOrderReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_shipping_service_v1_shipping_proto protoreflect.FileDescriptor

const file_shipping_service_v1_shipping_proto_rawDesc = "" +
	"\n" +
	"\"shipping/service/v1/shipping.proto\x12\x13shipping.service.v1\x1a\x1cgoogle/api/annotations.proto\"\x1e\n" +
	"\fShipOrderReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\" \n" +
	"\x0eShipOrderReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id2a\n" +
	"\bShipping\x12U\n" +
	"\tShipOrder\x12!.shipping.service.v1.ShipOrderReq\x1a#.shipping.service.v1.ShipOrderReply\"\x00B\xdb\x01\n" +
	"\x17com.shipping.service.v1B\rShippingProtoP\x01ZCtlgitea.com/pingtai/gopkg/api/_gen/go/shipping/service/v1;servicev1\xa2\x02\x03SSX\xaa\x02\x13Shipping.Service.V1\xca\x02\x13Shipping\\Service\\V1\xe2\x02\x1fShipping\\Service\\V1\\GPBMetadata\xea\x02\x15Shipping::Service::V1b\x06proto3"

var (
	file_shipping_service_v1_shipping_proto_rawDescOnce sync.Once
	file_shipping_service_v1_shipping_proto_rawDescData []byte
)

func file_shipping_service_v1_shipping_proto_rawDescGZIP() []byte {
	file_shipping_service_v1_shipping_proto_rawDescOnce.Do(func() {
		file_shipping_service_v1_shipping_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shipping_service_v1_shipping_proto_rawDesc), len(file_shipping_service_v1_shipping_proto_rawDesc)))
	})
	return file_shipping_service_v1_shipping_proto_rawDescData
}

var file_shipping_service_v1_shipping_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shipping_service_v1_shipping_proto_goTypes = []any{
	(*ShipOrderReq)(nil),   // 0: shipping.service.v1.ShipOrderReq
	(*ShipOrderReply)(nil), // 1: shipping.service.v1.ShipOrderReply
}
var file_shipping_service_v1_shipping_proto_depIdxs = []int32{
	0, // 0: shipping.service.v1.Shipping.ShipOrder:input_type -> shipping.service.v1.ShipOrderReq
	1, // 1: shipping.service.v1.Shipping.ShipOrder:output_type -> shipping.service.v1.ShipOrderReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shipping_service_v1_shipping_proto_init() }
func file_shipping_service_v1_shipping_proto_init() {
	if File_shipping_service_v1_shipping_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shipping_service_v1_shipping_proto_rawDesc), len(file_shipping_service_v1_shipping_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shipping_service_v1_shipping_proto_goTypes,
		DependencyIndexes: file_shipping_service_v1_shipping_proto_depIdxs,
		MessageInfos:      file_shipping_service_v1_shipping_proto_msgTypes,
	}.Build()
	File_shipping_service_v1_shipping_proto = out.File
	file_shipping_service_v1_shipping_proto_goTypes = nil
	file_shipping_service_v1_shipping_proto_depIdxs = nil
}
