// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: user/service/v1/user.proto

package servicev1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserReq) Reset() {
	*x = GetUserReq{}
	mi := &file_user_service_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReq) ProtoMessage() {}

func (x *GetUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReq.ProtoReflect.Descriptor instead.
func (*GetUserReq) Descriptor() ([]byte, []int) {
	return file_user_service_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserReply) Reset() {
	*x = GetUserReply{}
	mi := &file_user_service_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReply) ProtoMessage() {}

func (x *GetUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReply.ProtoReflect.Descriptor instead.
func (*GetUserReply) Descriptor() ([]byte, []int) {
	return file_user_service_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetUserReply) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetUserByUsernameReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByUsernameReq) Reset() {
	*x = GetUserByUsernameReq{}
	mi := &file_user_service_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByUsernameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByUsernameReq) ProtoMessage() {}

func (x *GetUserByUsernameReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByUsernameReq.ProtoReflect.Descriptor instead.
func (*GetUserByUsernameReq) Descriptor() ([]byte, []int) {
	return file_user_service_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserByUsernameReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetUserByUsernameReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByUsernameReply) Reset() {
	*x = GetUserByUsernameReply{}
	mi := &file_user_service_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByUsernameReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByUsernameReply) ProtoMessage() {}

func (x *GetUserByUsernameReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByUsernameReply.ProtoReflect.Descriptor instead.
func (*GetUserByUsernameReply) Descriptor() ([]byte, []int) {
	return file_user_service_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserByUsernameReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetUserByUsernameReply) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type CreateUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserReq) Reset() {
	*x = CreateUserReq{}
	mi := &file_user_service_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserReq) ProtoMessage() {}

func (x *CreateUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserReq.ProtoReflect.Descriptor instead.
func (*CreateUserReq) Descriptor() ([]byte, []int) {
	return file_user_service_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *CreateUserReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreateUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserReply) Reset() {
	*x = CreateUserReply{}
	mi := &file_user_service_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserReply) ProtoMessage() {}

func (x *CreateUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserReply.ProtoReflect.Descriptor instead.
func (*CreateUserReply) Descriptor() ([]byte, []int) {
	return file_user_service_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *CreateUserReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateUserReply) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ListUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserReq) Reset() {
	*x = ListUserReq{}
	mi := &file_user_service_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserReq) ProtoMessage() {}

func (x *ListUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserReq.ProtoReflect.Descriptor instead.
func (*ListUserReq) Descriptor() ([]byte, []int) {
	return file_user_service_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *ListUserReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ListUserReply_User  `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserReply) Reset() {
	*x = ListUserReply{}
	mi := &file_user_service_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserReply) ProtoMessage() {}

func (x *ListUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserReply.ProtoReflect.Descriptor instead.
func (*ListUserReply) Descriptor() ([]byte, []int) {
	return file_user_service_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *ListUserReply) GetResults() []*ListUserReply_User {
	if x != nil {
		return x.Results
	}
	return nil
}

type VerifyPasswordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPasswordReq) Reset() {
	*x = VerifyPasswordReq{}
	mi := &file_user_service_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPasswordReq) ProtoMessage() {}

func (x *VerifyPasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPasswordReq.ProtoReflect.Descriptor instead.
func (*VerifyPasswordReq) Descriptor() ([]byte, []int) {
	return file_user_service_v1_user_proto_rawDescGZIP(), []int{8}
}

func (x *VerifyPasswordReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *VerifyPasswordReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type VerifyPasswordReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPasswordReply) Reset() {
	*x = VerifyPasswordReply{}
	mi := &file_user_service_v1_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPasswordReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPasswordReply) ProtoMessage() {}

func (x *VerifyPasswordReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_v1_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPasswordReply.ProtoReflect.Descriptor instead.
func (*VerifyPasswordReply) Descriptor() ([]byte, []int) {
	return file_user_service_v1_user_proto_rawDescGZIP(), []int{9}
}

func (x *VerifyPasswordReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *VerifyPasswordReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListAddressReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAddressReq) Reset() {
	*x = ListAddressReq{}
	mi := &file_user_service_v1_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAddressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAddressReq) ProtoMessage() {}

func (x *ListAddressReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_v1_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAddressReq.ProtoReflect.Descriptor instead.
func (*ListAddressReq) Descriptor() ([]byte, []int) {
	return file_user_service_v1_user_proto_rawDescGZIP(), []int{10}
}

func (x *ListAddressReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type ListAddressReply struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Results       []*ListAddressReply_Address `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAddressReply) Reset() {
	*x = ListAddressReply{}
	mi := &file_user_service_v1_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAddressReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAddressReply) ProtoMessage() {}

func (x *ListAddressReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_v1_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAddressReply.ProtoReflect.Descriptor instead.
func (*ListAddressReply) Descriptor() ([]byte, []int) {
	return file_user_service_v1_user_proto_rawDescGZIP(), []int{11}
}

func (x *ListAddressReply) GetResults() []*ListAddressReply_Address {
	if x != nil {
		return x.Results
	}
	return nil
}

type CreateAddressReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mobile        string                 `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	PostCode      string                 `protobuf:"bytes,5,opt,name=post_code,json=postCode,proto3" json:"post_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAddressReq) Reset() {
	*x = CreateAddressReq{}
	mi := &file_user_service_v1_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAddressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAddressReq) ProtoMessage() {}

func (x *CreateAddressReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_v1_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAddressReq.ProtoReflect.Descriptor instead.
func (*CreateAddressReq) Descriptor() ([]byte, []int) {
	return file_user_service_v1_user_proto_rawDescGZIP(), []int{12}
}

func (x *CreateAddressReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CreateAddressReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAddressReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *CreateAddressReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateAddressReq) GetPostCode() string {
	if x != nil {
		return x.PostCode
	}
	return ""
}

type CreateAddressReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mobile        string                 `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	PostCode      string                 `protobuf:"bytes,5,opt,name=post_code,json=postCode,proto3" json:"post_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAddressReply) Reset() {
	*x = CreateAddressReply{}
	mi := &file_user_service_v1_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAddressReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAddressReply) ProtoMessage() {}

func (x *CreateAddressReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_v1_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAddressReply.ProtoReflect.Descriptor instead.
func (*CreateAddressReply) Descriptor() ([]byte, []int) {
	return file_user_service_v1_user_proto_rawDescGZIP(), []int{13}
}

func (x *CreateAddressReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateAddressReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAddressReply) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *CreateAddressReply) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateAddressReply) GetPostCode() string {
	if x != nil {
		return x.PostCode
	}
	return ""
}

type GetAddressReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressReq) Reset() {
	*x = GetAddressReq{}
	mi := &file_user_service_v1_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressReq) ProtoMessage() {}

func (x *GetAddressReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_v1_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressReq.ProtoReflect.Descriptor instead.
func (*GetAddressReq) Descriptor() ([]byte, []int) {
	return file_user_service_v1_user_proto_rawDescGZIP(), []int{14}
}

func (x *GetAddressReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAddressReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mobile        string                 `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	PostCode      string                 `protobuf:"bytes,5,opt,name=post_code,json=postCode,proto3" json:"post_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressReply) Reset() {
	*x = GetAddressReply{}
	mi := &file_user_service_v1_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressReply) ProtoMessage() {}

func (x *GetAddressReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_v1_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressReply.ProtoReflect.Descriptor instead.
func (*GetAddressReply) Descriptor() ([]byte, []int) {
	return file_user_service_v1_user_proto_rawDescGZIP(), []int{15}
}

func (x *GetAddressReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetAddressReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetAddressReply) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *GetAddressReply) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetAddressReply) GetPostCode() string {
	if x != nil {
		return x.PostCode
	}
	return ""
}

type ListCardReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCardReq) Reset() {
	*x = ListCardReq{}
	mi := &file_user_service_v1_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCardReq) ProtoMessage() {}

func (x *ListCardReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_v1_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCardReq.ProtoReflect.Descriptor instead.
func (*ListCardReq) Descriptor() ([]byte, []int) {
	return file_user_service_v1_user_proto_rawDescGZIP(), []int{16}
}

func (x *ListCardReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type ListCardReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ListCardReply_Card  `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCardReply) Reset() {
	*x = ListCardReply{}
	mi := &file_user_service_v1_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCardReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCardReply) ProtoMessage() {}

func (x *ListCardReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_v1_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCardReply.ProtoReflect.Descriptor instead.
func (*ListCardReply) Descriptor() ([]byte, []int) {
	return file_user_service_v1_user_proto_rawDescGZIP(), []int{17}
}

func (x *ListCardReply) GetResults() []*ListCardReply_Card {
	if x != nil {
		return x.Results
	}
	return nil
}

type CreateCardReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	CardNo        string                 `protobuf:"bytes,2,opt,name=card_no,json=cardNo,proto3" json:"card_no,omitempty"`
	Ccv           string                 `protobuf:"bytes,3,opt,name=ccv,proto3" json:"ccv,omitempty"`
	Expires       string                 `protobuf:"bytes,4,opt,name=expires,proto3" json:"expires,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCardReq) Reset() {
	*x = CreateCardReq{}
	mi := &file_user_service_v1_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCardReq) ProtoMessage() {}

func (x *CreateCardReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_v1_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCardReq.ProtoReflect.Descriptor instead.
func (*CreateCardReq) Descriptor() ([]byte, []int) {
	return file_user_service_v1_user_proto_rawDescGZIP(), []int{18}
}

func (x *CreateCardReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CreateCardReq) GetCardNo() string {
	if x != nil {
		return x.CardNo
	}
	return ""
}

func (x *CreateCardReq) GetCcv() string {
	if x != nil {
		return x.Ccv
	}
	return ""
}

func (x *CreateCardReq) GetExpires() string {
	if x != nil {
		return x.Expires
	}
	return ""
}

func (x *CreateCardReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateCardReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCardReply) Reset() {
	*x = CreateCardReply{}
	mi := &file_user_service_v1_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCardReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCardReply) ProtoMessage() {}

func (x *CreateCardReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_v1_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCardReply.ProtoReflect.Descriptor instead.
func (*CreateCardReply) Descriptor() ([]byte, []int) {
	return file_user_service_v1_user_proto_rawDescGZIP(), []int{19}
}

func (x *CreateCardReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetCardReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardReq) Reset() {
	*x = GetCardReq{}
	mi := &file_user_service_v1_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardReq) ProtoMessage() {}

func (x *GetCardReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_v1_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardReq.ProtoReflect.Descriptor instead.
func (*GetCardReq) Descriptor() ([]byte, []int) {
	return file_user_service_v1_user_proto_rawDescGZIP(), []int{20}
}

func (x *GetCardReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetCardReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CardNo        string                 `protobuf:"bytes,2,opt,name=card_no,json=cardNo,proto3" json:"card_no,omitempty"`
	Ccv           string                 `protobuf:"bytes,3,opt,name=ccv,proto3" json:"ccv,omitempty"`
	Expires       string                 `protobuf:"bytes,4,opt,name=expires,proto3" json:"expires,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardReply) Reset() {
	*x = GetCardReply{}
	mi := &file_user_service_v1_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardReply) ProtoMessage() {}

func (x *GetCardReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_v1_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardReply.ProtoReflect.Descriptor instead.
func (*GetCardReply) Descriptor() ([]byte, []int) {
	return file_user_service_v1_user_proto_rawDescGZIP(), []int{21}
}

func (x *GetCardReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetCardReply) GetCardNo() string {
	if x != nil {
		return x.CardNo
	}
	return ""
}

func (x *GetCardReply) GetCcv() string {
	if x != nil {
		return x.Ccv
	}
	return ""
}

func (x *GetCardReply) GetExpires() string {
	if x != nil {
		return x.Expires
	}
	return ""
}

type DeleteCardReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCardReq) Reset() {
	*x = DeleteCardReq{}
	mi := &file_user_service_v1_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCardReq) ProtoMessage() {}

func (x *DeleteCardReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_v1_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCardReq.ProtoReflect.Descriptor instead.
func (*DeleteCardReq) Descriptor() ([]byte, []int) {
	return file_user_service_v1_user_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteCardReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *DeleteCardReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteCardReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCardReply) Reset() {
	*x = DeleteCardReply{}
	mi := &file_user_service_v1_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCardReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCardReply) ProtoMessage() {}

func (x *DeleteCardReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_v1_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCardReply.ProtoReflect.Descriptor instead.
func (*DeleteCardReply) Descriptor() ([]byte, []int) {
	return file_user_service_v1_user_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteCardReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type SaveUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveUserReq) Reset() {
	*x = SaveUserReq{}
	mi := &file_user_service_v1_user_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveUserReq) ProtoMessage() {}

func (x *SaveUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_v1_user_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveUserReq.ProtoReflect.Descriptor instead.
func (*SaveUserReq) Descriptor() ([]byte, []int) {
	return file_user_service_v1_user_proto_rawDescGZIP(), []int{24}
}

func (x *SaveUserReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SaveUserReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SaveUserReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SaveUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveUserReply) Reset() {
	*x = SaveUserReply{}
	mi := &file_user_service_v1_user_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveUserReply) ProtoMessage() {}

func (x *SaveUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_v1_user_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveUserReply.ProtoReflect.Descriptor instead.
func (*SaveUserReply) Descriptor() ([]byte, []int) {
	return file_user_service_v1_user_proto_rawDescGZIP(), []int{25}
}

func (x *SaveUserReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListUserReply_User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserReply_User) Reset() {
	*x = ListUserReply_User{}
	mi := &file_user_service_v1_user_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserReply_User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserReply_User) ProtoMessage() {}

func (x *ListUserReply_User) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_v1_user_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserReply_User.ProtoReflect.Descriptor instead.
func (*ListUserReply_User) Descriptor() ([]byte, []int) {
	return file_user_service_v1_user_proto_rawDescGZIP(), []int{7, 0}
}

func (x *ListUserReply_User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListUserReply_User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListAddressReply_Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mobile        string                 `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	PostCode      string                 `protobuf:"bytes,5,opt,name=post_code,json=postCode,proto3" json:"post_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAddressReply_Address) Reset() {
	*x = ListAddressReply_Address{}
	mi := &file_user_service_v1_user_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAddressReply_Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAddressReply_Address) ProtoMessage() {}

func (x *ListAddressReply_Address) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_v1_user_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAddressReply_Address.ProtoReflect.Descriptor instead.
func (*ListAddressReply_Address) Descriptor() ([]byte, []int) {
	return file_user_service_v1_user_proto_rawDescGZIP(), []int{11, 0}
}

func (x *ListAddressReply_Address) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListAddressReply_Address) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListAddressReply_Address) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *ListAddressReply_Address) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ListAddressReply_Address) GetPostCode() string {
	if x != nil {
		return x.PostCode
	}
	return ""
}

type ListCardReply_Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CardNo        string                 `protobuf:"bytes,2,opt,name=card_no,json=cardNo,proto3" json:"card_no,omitempty"`
	Ccv           string                 `protobuf:"bytes,3,opt,name=ccv,proto3" json:"ccv,omitempty"`
	Expires       string                 `protobuf:"bytes,4,opt,name=expires,proto3" json:"expires,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCardReply_Card) Reset() {
	*x = ListCardReply_Card{}
	mi := &file_user_service_v1_user_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCardReply_Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCardReply_Card) ProtoMessage() {}

func (x *ListCardReply_Card) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_v1_user_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCardReply_Card.ProtoReflect.Descriptor instead.
func (*ListCardReply_Card) Descriptor() ([]byte, []int) {
	return file_user_service_v1_user_proto_rawDescGZIP(), []int{17, 0}
}

func (x *ListCardReply_Card) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListCardReply_Card) GetCardNo() string {
	if x != nil {
		return x.CardNo
	}
	return ""
}

func (x *ListCardReply_Card) GetCcv() string {
	if x != nil {
		return x.Ccv
	}
	return ""
}

func (x *ListCardReply_Card) GetExpires() string {
	if x != nil {
		return x.Expires
	}
	return ""
}

var File_user_service_v1_user_proto protoreflect.FileDescriptor

const file_user_service_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x1auser/service/v1/user.proto\x12\x0fuser.service.v1\x1a\x1cgoogle/api/annotations.proto\"\x1c\n" +
	"\n" +
	"GetUserReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\":\n" +
	"\fGetUserReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"2\n" +
	"\x14GetUserByUsernameReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"D\n" +
	"\x16GetUserByUsernameReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"G\n" +
	"\rCreateUserReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"=\n" +
	"\x0fCreateUserReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"\x1d\n" +
	"\vListUserReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"z\n" +
	"\rListUserReply\x12=\n" +
	"\aresults\x18\x01 \x03(\v2#.user.service.v1.ListUserReply.UserR\aresults\x1a*\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"K\n" +
	"\x11VerifyPasswordReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"5\n" +
	"\x13VerifyPasswordReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\"\"\n" +
	"\x0eListAddressReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\"\xd5\x01\n" +
	"\x10ListAddressReply\x12C\n" +
	"\aresults\x18\x01 \x03(\v2).user.service.v1.ListAddressReply.AddressR\aresults\x1a|\n" +
	"\aAddress\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06mobile\x18\x03 \x01(\tR\x06mobile\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x1b\n" +
	"\tpost_code\x18\x05 \x01(\tR\bpostCode\"\x87\x01\n" +
	"\x10CreateAddressReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06mobile\x18\x03 \x01(\tR\x06mobile\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x1b\n" +
	"\tpost_code\x18\x05 \x01(\tR\bpostCode\"\x87\x01\n" +
	"\x12CreateAddressReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06mobile\x18\x03 \x01(\tR\x06mobile\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x1b\n" +
	"\tpost_code\x18\x05 \x01(\tR\bpostCode\"\x1f\n" +
	"\rGetAddressReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x84\x01\n" +
	"\x0fGetAddressReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06mobile\x18\x03 \x01(\tR\x06mobile\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x1b\n" +
	"\tpost_code\x18\x05 \x01(\tR\bpostCode\"\x1f\n" +
	"\vListCardReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\"\xab\x01\n" +
	"\rListCardReply\x12=\n" +
	"\aresults\x18\x01 \x03(\v2#.user.service.v1.ListCardReply.CardR\aresults\x1a[\n" +
	"\x04Card\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\acard_no\x18\x02 \x01(\tR\x06cardNo\x12\x10\n" +
	"\x03ccv\x18\x03 \x01(\tR\x03ccv\x12\x18\n" +
	"\aexpires\x18\x04 \x01(\tR\aexpires\"z\n" +
	"\rCreateCardReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x17\n" +
	"\acard_no\x18\x02 \x01(\tR\x06cardNo\x12\x10\n" +
	"\x03ccv\x18\x03 \x01(\tR\x03ccv\x12\x18\n" +
	"\aexpires\x18\x04 \x01(\tR\aexpires\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\"!\n" +
	"\x0fCreateCardReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x1c\n" +
	"\n" +
	"GetCardReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"c\n" +
	"\fGetCardReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\acard_no\x18\x02 \x01(\tR\x06cardNo\x12\x10\n" +
	"\x03ccv\x18\x03 \x01(\tR\x03ccv\x12\x18\n" +
	"\aexpires\x18\x04 \x01(\tR\aexpires\"1\n" +
	"\rDeleteCardReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\"!\n" +
	"\x0fDeleteCardReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"U\n" +
	"\vSaveUserReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"\x1f\n" +
	"\rSaveUserReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id2\xb5\b\n" +
	"\x04User\x12G\n" +
	"\aGetUser\x12\x1b.user.service.v1.GetUserReq\x1a\x1d.user.service.v1.GetUserReply\"\x00\x12e\n" +
	"\x11GetUserByUsername\x12%.user.service.v1.GetUserByUsernameReq\x1a'.user.service.v1.GetUserByUsernameReply\"\x00\x12F\n" +
	"\x04Save\x12\x1c.user.service.v1.SaveUserReq\x1a\x1e.user.service.v1.SaveUserReply\"\x00\x12P\n" +
	"\n" +
	"CreateUser\x12\x1e.user.service.v1.CreateUserReq\x1a .user.service.v1.CreateUserReply\"\x00\x12J\n" +
	"\bListUser\x12\x1c.user.service.v1.ListUserReq\x1a\x1e.user.service.v1.ListUserReply\"\x00\x12\\\n" +
	"\x0eVerifyPassword\x12\".user.service.v1.VerifyPasswordReq\x1a$.user.service.v1.VerifyPasswordReply\"\x00\x12S\n" +
	"\vListAddress\x12\x1f.user.service.v1.ListAddressReq\x1a!.user.service.v1.ListAddressReply\"\x00\x12Y\n" +
	"\rCreateAddress\x12!.user.service.v1.CreateAddressReq\x1a#.user.service.v1.CreateAddressReply\"\x00\x12P\n" +
	"\n" +
	"GetAddress\x12\x1e.user.service.v1.GetAddressReq\x1a .user.service.v1.GetAddressReply\"\x00\x12J\n" +
	"\bListCard\x12\x1c.user.service.v1.ListCardReq\x1a\x1e.user.service.v1.ListCardReply\"\x00\x12P\n" +
	"\n" +
	"CreateCard\x12\x1e.user.service.v1.CreateCardReq\x1a .user.service.v1.CreateCardReply\"\x00\x12G\n" +
	"\aGetCard\x12\x1b.user.service.v1.GetCardReq\x1a\x1d.user.service.v1.GetCardReply\"\x00\x12P\n" +
	"\n" +
	"DeleteCard\x12\x1e.user.service.v1.DeleteCardReq\x1a .user.service.v1.DeleteCardReply\"\x00B\xbf\x01\n" +
	"\x13com.user.service.v1B\tUserProtoP\x01Z?tlgitea.com/pingtai/gopkg/api/_gen/go/user/service/v1;servicev1\xa2\x02\x03USX\xaa\x02\x0fUser.Service.V1\xca\x02\x0fUser\\Service\\V1\xe2\x02\x1bUser\\Service\\V1\\GPBMetadata\xea\x02\x11User::Service::V1b\x06proto3"

var (
	file_user_service_v1_user_proto_rawDescOnce sync.Once
	file_user_service_v1_user_proto_rawDescData []byte
)

func file_user_service_v1_user_proto_rawDescGZIP() []byte {
	file_user_service_v1_user_proto_rawDescOnce.Do(func() {
		file_user_service_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_service_v1_user_proto_rawDesc), len(file_user_service_v1_user_proto_rawDesc)))
	})
	return file_user_service_v1_user_proto_rawDescData
}

var file_user_service_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_user_service_v1_user_proto_goTypes = []any{
	(*GetUserReq)(nil),               // 0: user.service.v1.GetUserReq
	(*GetUserReply)(nil),             // 1: user.service.v1.GetUserReply
	(*GetUserByUsernameReq)(nil),     // 2: user.service.v1.GetUserByUsernameReq
	(*GetUserByUsernameReply)(nil),   // 3: user.service.v1.GetUserByUsernameReply
	(*CreateUserReq)(nil),            // 4: user.service.v1.CreateUserReq
	(*CreateUserReply)(nil),          // 5: user.service.v1.CreateUserReply
	(*ListUserReq)(nil),              // 6: user.service.v1.ListUserReq
	(*ListUserReply)(nil),            // 7: user.service.v1.ListUserReply
	(*VerifyPasswordReq)(nil),        // 8: user.service.v1.VerifyPasswordReq
	(*VerifyPasswordReply)(nil),      // 9: user.service.v1.VerifyPasswordReply
	(*ListAddressReq)(nil),           // 10: user.service.v1.ListAddressReq
	(*ListAddressReply)(nil),         // 11: user.service.v1.ListAddressReply
	(*CreateAddressReq)(nil),         // 12: user.service.v1.CreateAddressReq
	(*CreateAddressReply)(nil),       // 13: user.service.v1.CreateAddressReply
	(*GetAddressReq)(nil),            // 14: user.service.v1.GetAddressReq
	(*GetAddressReply)(nil),          // 15: user.service.v1.GetAddressReply
	(*ListCardReq)(nil),              // 16: user.service.v1.ListCardReq
	(*ListCardReply)(nil),            // 17: user.service.v1.ListCardReply
	(*CreateCardReq)(nil),            // 18: user.service.v1.CreateCardReq
	(*CreateCardReply)(nil),          // 19: user.service.v1.CreateCardReply
	(*GetCardReq)(nil),               // 20: user.service.v1.GetCardReq
	(*GetCardReply)(nil),             // 21: user.service.v1.GetCardReply
	(*DeleteCardReq)(nil),            // 22: user.service.v1.DeleteCardReq
	(*DeleteCardReply)(nil),          // 23: user.service.v1.DeleteCardReply
	(*SaveUserReq)(nil),              // 24: user.service.v1.SaveUserReq
	(*SaveUserReply)(nil),            // 25: user.service.v1.SaveUserReply
	(*ListUserReply_User)(nil),       // 26: user.service.v1.ListUserReply.User
	(*ListAddressReply_Address)(nil), // 27: user.service.v1.ListAddressReply.Address
	(*ListCardReply_Card)(nil),       // 28: user.service.v1.ListCardReply.Card
}
var file_user_service_v1_user_proto_depIdxs = []int32{
	26, // 0: user.service.v1.ListUserReply.results:type_name -> user.service.v1.ListUserReply.User
	27, // 1: user.service.v1.ListAddressReply.results:type_name -> user.service.v1.ListAddressReply.Address
	28, // 2: user.service.v1.ListCardReply.results:type_name -> user.service.v1.ListCardReply.Card
	0,  // 3: user.service.v1.User.GetUser:input_type -> user.service.v1.GetUserReq
	2,  // 4: user.service.v1.User.GetUserByUsername:input_type -> user.service.v1.GetUserByUsernameReq
	24, // 5: user.service.v1.User.Save:input_type -> user.service.v1.SaveUserReq
	4,  // 6: user.service.v1.User.CreateUser:input_type -> user.service.v1.CreateUserReq
	6,  // 7: user.service.v1.User.ListUser:input_type -> user.service.v1.ListUserReq
	8,  // 8: user.service.v1.User.VerifyPassword:input_type -> user.service.v1.VerifyPasswordReq
	10, // 9: user.service.v1.User.ListAddress:input_type -> user.service.v1.ListAddressReq
	12, // 10: user.service.v1.User.CreateAddress:input_type -> user.service.v1.CreateAddressReq
	14, // 11: user.service.v1.User.GetAddress:input_type -> user.service.v1.GetAddressReq
	16, // 12: user.service.v1.User.ListCard:input_type -> user.service.v1.ListCardReq
	18, // 13: user.service.v1.User.CreateCard:input_type -> user.service.v1.CreateCardReq
	20, // 14: user.service.v1.User.GetCard:input_type -> user.service.v1.GetCardReq
	22, // 15: user.service.v1.User.DeleteCard:input_type -> user.service.v1.DeleteCardReq
	1,  // 16: user.service.v1.User.GetUser:output_type -> user.service.v1.GetUserReply
	3,  // 17: user.service.v1.User.GetUserByUsername:output_type -> user.service.v1.GetUserByUsernameReply
	25, // 18: user.service.v1.User.Save:output_type -> user.service.v1.SaveUserReply
	5,  // 19: user.service.v1.User.CreateUser:output_type -> user.service.v1.CreateUserReply
	7,  // 20: user.service.v1.User.ListUser:output_type -> user.service.v1.ListUserReply
	9,  // 21: user.service.v1.User.VerifyPassword:output_type -> user.service.v1.VerifyPasswordReply
	11, // 22: user.service.v1.User.ListAddress:output_type -> user.service.v1.ListAddressReply
	13, // 23: user.service.v1.User.CreateAddress:output_type -> user.service.v1.CreateAddressReply
	15, // 24: user.service.v1.User.GetAddress:output_type -> user.service.v1.GetAddressReply
	17, // 25: user.service.v1.User.ListCard:output_type -> user.service.v1.ListCardReply
	19, // 26: user.service.v1.User.CreateCard:output_type -> user.service.v1.CreateCardReply
	21, // 27: user.service.v1.User.GetCard:output_type -> user.service.v1.GetCardReply
	23, // 28: user.service.v1.User.DeleteCard:output_type -> user.service.v1.DeleteCardReply
	16, // [16:29] is the sub-list for method output_type
	3,  // [3:16] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_user_service_v1_user_proto_init() }
func file_user_service_v1_user_proto_init() {
	if File_user_service_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_service_v1_user_proto_rawDesc), len(file_user_service_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_service_v1_user_proto_goTypes,
		DependencyIndexes: file_user_service_v1_user_proto_depIdxs,
		MessageInfos:      file_user_service_v1_user_proto_msgTypes,
	}.Build()
	File_user_service_v1_user_proto = out.File
	file_user_service_v1_user_proto_goTypes = nil
	file_user_service_v1_user_proto_depIdxs = nil
}
