// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cart/service/v1/cart.proto

package servicev1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCartReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartReq) Reset() {
	*x = GetCartReq{}
	mi := &file_cart_service_v1_cart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartReq) ProtoMessage() {}

func (x *GetCartReq) ProtoReflect() protoreflect.Message {
	mi := &file_cart_service_v1_cart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartReq.ProtoReflect.Descriptor instead.
func (*GetCartReq) Descriptor() ([]byte, []int) {
	return file_cart_service_v1_cart_proto_rawDescGZIP(), []int{0}
}

func (x *GetCartReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetCartReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*GetCartReply_Item   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartReply) Reset() {
	*x = GetCartReply{}
	mi := &file_cart_service_v1_cart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartReply) ProtoMessage() {}

func (x *GetCartReply) ProtoReflect() protoreflect.Message {
	mi := &file_cart_service_v1_cart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartReply.ProtoReflect.Descriptor instead.
func (*GetCartReply) Descriptor() ([]byte, []int) {
	return file_cart_service_v1_cart_proto_rawDescGZIP(), []int{1}
}

func (x *GetCartReply) GetItems() []*GetCartReply_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type DeleteCartReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCartReq) Reset() {
	*x = DeleteCartReq{}
	mi := &file_cart_service_v1_cart_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCartReq) ProtoMessage() {}

func (x *DeleteCartReq) ProtoReflect() protoreflect.Message {
	mi := &file_cart_service_v1_cart_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCartReq.ProtoReflect.Descriptor instead.
func (*DeleteCartReq) Descriptor() ([]byte, []int) {
	return file_cart_service_v1_cart_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteCartReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteCartReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCartReply) Reset() {
	*x = DeleteCartReply{}
	mi := &file_cart_service_v1_cart_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCartReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCartReply) ProtoMessage() {}

func (x *DeleteCartReply) ProtoReflect() protoreflect.Message {
	mi := &file_cart_service_v1_cart_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCartReply.ProtoReflect.Descriptor instead.
func (*DeleteCartReply) Descriptor() ([]byte, []int) {
	return file_cart_service_v1_cart_proto_rawDescGZIP(), []int{3}
}

type AddItemReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ItemId        int64                  `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemReq) Reset() {
	*x = AddItemReq{}
	mi := &file_cart_service_v1_cart_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemReq) ProtoMessage() {}

func (x *AddItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_cart_service_v1_cart_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemReq.ProtoReflect.Descriptor instead.
func (*AddItemReq) Descriptor() ([]byte, []int) {
	return file_cart_service_v1_cart_proto_rawDescGZIP(), []int{4}
}

func (x *AddItemReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddItemReq) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *AddItemReq) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type AddItemReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*AddItemReply_Item   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemReply) Reset() {
	*x = AddItemReply{}
	mi := &file_cart_service_v1_cart_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemReply) ProtoMessage() {}

func (x *AddItemReply) ProtoReflect() protoreflect.Message {
	mi := &file_cart_service_v1_cart_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemReply.ProtoReflect.Descriptor instead.
func (*AddItemReply) Descriptor() ([]byte, []int) {
	return file_cart_service_v1_cart_proto_rawDescGZIP(), []int{5}
}

func (x *AddItemReply) GetItems() []*AddItemReply_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type UpdateItemReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ItemId        int64                  `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemReq) Reset() {
	*x = UpdateItemReq{}
	mi := &file_cart_service_v1_cart_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemReq) ProtoMessage() {}

func (x *UpdateItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_cart_service_v1_cart_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemReq.ProtoReflect.Descriptor instead.
func (*UpdateItemReq) Descriptor() ([]byte, []int) {
	return file_cart_service_v1_cart_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateItemReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateItemReq) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *UpdateItemReq) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type UpdateItemReply struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Items         []*UpdateItemReply_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemReply) Reset() {
	*x = UpdateItemReply{}
	mi := &file_cart_service_v1_cart_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemReply) ProtoMessage() {}

func (x *UpdateItemReply) ProtoReflect() protoreflect.Message {
	mi := &file_cart_service_v1_cart_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemReply.ProtoReflect.Descriptor instead.
func (*UpdateItemReply) Descriptor() ([]byte, []int) {
	return file_cart_service_v1_cart_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateItemReply) GetItems() []*UpdateItemReply_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type DeleteItemReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ItemId        int64                  `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemReq) Reset() {
	*x = DeleteItemReq{}
	mi := &file_cart_service_v1_cart_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemReq) ProtoMessage() {}

func (x *DeleteItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_cart_service_v1_cart_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemReq.ProtoReflect.Descriptor instead.
func (*DeleteItemReq) Descriptor() ([]byte, []int) {
	return file_cart_service_v1_cart_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteItemReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteItemReq) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

type DeleteItemReply struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Items         []*DeleteItemReply_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemReply) Reset() {
	*x = DeleteItemReply{}
	mi := &file_cart_service_v1_cart_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemReply) ProtoMessage() {}

func (x *DeleteItemReply) ProtoReflect() protoreflect.Message {
	mi := &file_cart_service_v1_cart_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemReply.ProtoReflect.Descriptor instead.
func (*DeleteItemReply) Descriptor() ([]byte, []int) {
	return file_cart_service_v1_cart_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteItemReply) GetItems() []*DeleteItemReply_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetCartReply_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int64                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartReply_Item) Reset() {
	*x = GetCartReply_Item{}
	mi := &file_cart_service_v1_cart_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartReply_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartReply_Item) ProtoMessage() {}

func (x *GetCartReply_Item) ProtoReflect() protoreflect.Message {
	mi := &file_cart_service_v1_cart_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartReply_Item.ProtoReflect.Descriptor instead.
func (*GetCartReply_Item) Descriptor() ([]byte, []int) {
	return file_cart_service_v1_cart_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetCartReply_Item) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *GetCartReply_Item) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type AddItemReply_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int64                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemReply_Item) Reset() {
	*x = AddItemReply_Item{}
	mi := &file_cart_service_v1_cart_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemReply_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemReply_Item) ProtoMessage() {}

func (x *AddItemReply_Item) ProtoReflect() protoreflect.Message {
	mi := &file_cart_service_v1_cart_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemReply_Item.ProtoReflect.Descriptor instead.
func (*AddItemReply_Item) Descriptor() ([]byte, []int) {
	return file_cart_service_v1_cart_proto_rawDescGZIP(), []int{5, 0}
}

func (x *AddItemReply_Item) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *AddItemReply_Item) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type UpdateItemReply_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int64                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemReply_Item) Reset() {
	*x = UpdateItemReply_Item{}
	mi := &file_cart_service_v1_cart_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemReply_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemReply_Item) ProtoMessage() {}

func (x *UpdateItemReply_Item) ProtoReflect() protoreflect.Message {
	mi := &file_cart_service_v1_cart_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemReply_Item.ProtoReflect.Descriptor instead.
func (*UpdateItemReply_Item) Descriptor() ([]byte, []int) {
	return file_cart_service_v1_cart_proto_rawDescGZIP(), []int{7, 0}
}

func (x *UpdateItemReply_Item) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *UpdateItemReply_Item) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type DeleteItemReply_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int64                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemReply_Item) Reset() {
	*x = DeleteItemReply_Item{}
	mi := &file_cart_service_v1_cart_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemReply_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemReply_Item) ProtoMessage() {}

func (x *DeleteItemReply_Item) ProtoReflect() protoreflect.Message {
	mi := &file_cart_service_v1_cart_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemReply_Item.ProtoReflect.Descriptor instead.
func (*DeleteItemReply_Item) Descriptor() ([]byte, []int) {
	return file_cart_service_v1_cart_proto_rawDescGZIP(), []int{9, 0}
}

func (x *DeleteItemReply_Item) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *DeleteItemReply_Item) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

var File_cart_service_v1_cart_proto protoreflect.FileDescriptor

const file_cart_service_v1_cart_proto_rawDesc = "" +
	"\n" +
	"\x1acart/service/v1/cart.proto\x12\x0fcart.service.v1\x1a\x1cgoogle/api/annotations.proto\"%\n" +
	"\n" +
	"GetCartReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\x85\x01\n" +
	"\fGetCartReply\x128\n" +
	"\x05items\x18\x01 \x03(\v2\".cart.service.v1.GetCartReply.ItemR\x05items\x1a;\n" +
	"\x04Item\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x03R\x06itemId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x03R\bquantity\"(\n" +
	"\rDeleteCartReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\x11\n" +
	"\x0fDeleteCartReply\"Z\n" +
	"\n" +
	"AddItemReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\x03R\x06itemId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\"\x85\x01\n" +
	"\fAddItemReply\x128\n" +
	"\x05items\x18\x01 \x03(\v2\".cart.service.v1.AddItemReply.ItemR\x05items\x1a;\n" +
	"\x04Item\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x03R\x06itemId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x03R\bquantity\"]\n" +
	"\rUpdateItemReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\x03R\x06itemId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\"\x8b\x01\n" +
	"\x0fUpdateItemReply\x12;\n" +
	"\x05items\x18\x01 \x03(\v2%.cart.service.v1.UpdateItemReply.ItemR\x05items\x1a;\n" +
	"\x04Item\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x03R\x06itemId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x03R\bquantity\"A\n" +
	"\rDeleteItemReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\x03R\x06itemId\"\x8b\x01\n" +
	"\x0fDeleteItemReply\x12;\n" +
	"\x05items\x18\x01 \x03(\v2%.cart.service.v1.DeleteItemReply.ItemR\x05items\x1a;\n" +
	"\x04Item\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x03R\x06itemId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x03R\bquantity2\x8e\x03\n" +
	"\x04Cart\x12G\n" +
	"\aGetCart\x12\x1b.cart.service.v1.GetCartReq\x1a\x1d.cart.service.v1.GetCartReply\"\x00\x12P\n" +
	"\n" +
	"DeleteCart\x12\x1e.cart.service.v1.DeleteCartReq\x1a .cart.service.v1.DeleteCartReply\"\x00\x12G\n" +
	"\aAddItem\x12\x1b.cart.service.v1.AddItemReq\x1a\x1d.cart.service.v1.AddItemReply\"\x00\x12P\n" +
	"\n" +
	"UpdateItem\x12\x1e.cart.service.v1.UpdateItemReq\x1a .cart.service.v1.UpdateItemReply\"\x00\x12P\n" +
	"\n" +
	"DeleteItem\x12\x1e.cart.service.v1.DeleteItemReq\x1a .cart.service.v1.DeleteItemReply\"\x00B\xbf\x01\n" +
	"\x13com.cart.service.v1B\tCartProtoP\x01Z?tlgitea.com/pingtai/gopkg/api/_gen/go/cart/service/v1;servicev1\xa2\x02\x03CSX\xaa\x02\x0fCart.Service.V1\xca\x02\x0fCart\\Service\\V1\xe2\x02\x1bCart\\Service\\V1\\GPBMetadata\xea\x02\x11Cart::Service::V1b\x06proto3"

var (
	file_cart_service_v1_cart_proto_rawDescOnce sync.Once
	file_cart_service_v1_cart_proto_rawDescData []byte
)

func file_cart_service_v1_cart_proto_rawDescGZIP() []byte {
	file_cart_service_v1_cart_proto_rawDescOnce.Do(func() {
		file_cart_service_v1_cart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cart_service_v1_cart_proto_rawDesc), len(file_cart_service_v1_cart_proto_rawDesc)))
	})
	return file_cart_service_v1_cart_proto_rawDescData
}

var file_cart_service_v1_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_cart_service_v1_cart_proto_goTypes = []any{
	(*GetCartReq)(nil),           // 0: cart.service.v1.GetCartReq
	(*GetCartReply)(nil),         // 1: cart.service.v1.GetCartReply
	(*DeleteCartReq)(nil),        // 2: cart.service.v1.DeleteCartReq
	(*DeleteCartReply)(nil),      // 3: cart.service.v1.DeleteCartReply
	(*AddItemReq)(nil),           // 4: cart.service.v1.AddItemReq
	(*AddItemReply)(nil),         // 5: cart.service.v1.AddItemReply
	(*UpdateItemReq)(nil),        // 6: cart.service.v1.UpdateItemReq
	(*UpdateItemReply)(nil),      // 7: cart.service.v1.UpdateItemReply
	(*DeleteItemReq)(nil),        // 8: cart.service.v1.DeleteItemReq
	(*DeleteItemReply)(nil),      // 9: cart.service.v1.DeleteItemReply
	(*GetCartReply_Item)(nil),    // 10: cart.service.v1.GetCartReply.Item
	(*AddItemReply_Item)(nil),    // 11: cart.service.v1.AddItemReply.Item
	(*UpdateItemReply_Item)(nil), // 12: cart.service.v1.UpdateItemReply.Item
	(*DeleteItemReply_Item)(nil), // 13: cart.service.v1.DeleteItemReply.Item
}
var file_cart_service_v1_cart_proto_depIdxs = []int32{
	10, // 0: cart.service.v1.GetCartReply.items:type_name -> cart.service.v1.GetCartReply.Item
	11, // 1: cart.service.v1.AddItemReply.items:type_name -> cart.service.v1.AddItemReply.Item
	12, // 2: cart.service.v1.UpdateItemReply.items:type_name -> cart.service.v1.UpdateItemReply.Item
	13, // 3: cart.service.v1.DeleteItemReply.items:type_name -> cart.service.v1.DeleteItemReply.Item
	0,  // 4: cart.service.v1.Cart.GetCart:input_type -> cart.service.v1.GetCartReq
	2,  // 5: cart.service.v1.Cart.DeleteCart:input_type -> cart.service.v1.DeleteCartReq
	4,  // 6: cart.service.v1.Cart.AddItem:input_type -> cart.service.v1.AddItemReq
	6,  // 7: cart.service.v1.Cart.UpdateItem:input_type -> cart.service.v1.UpdateItemReq
	8,  // 8: cart.service.v1.Cart.DeleteItem:input_type -> cart.service.v1.DeleteItemReq
	1,  // 9: cart.service.v1.Cart.GetCart:output_type -> cart.service.v1.GetCartReply
	3,  // 10: cart.service.v1.Cart.DeleteCart:output_type -> cart.service.v1.DeleteCartReply
	5,  // 11: cart.service.v1.Cart.AddItem:output_type -> cart.service.v1.AddItemReply
	7,  // 12: cart.service.v1.Cart.UpdateItem:output_type -> cart.service.v1.UpdateItemReply
	9,  // 13: cart.service.v1.Cart.DeleteItem:output_type -> cart.service.v1.DeleteItemReply
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_cart_service_v1_cart_proto_init() }
func file_cart_service_v1_cart_proto_init() {
	if File_cart_service_v1_cart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cart_service_v1_cart_proto_rawDesc), len(file_cart_service_v1_cart_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cart_service_v1_cart_proto_goTypes,
		DependencyIndexes: file_cart_service_v1_cart_proto_depIdxs,
		MessageInfos:      file_cart_service_v1_cart_proto_msgTypes,
	}.Build()
	File_cart_service_v1_cart_proto = out.File
	file_cart_service_v1_cart_proto_goTypes = nil
	file_cart_service_v1_cart_proto_depIdxs = nil
}
