// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cart/service/v1/cart_error.proto

package servicev1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CartServiceErrorReason int32

const (
	CartServiceErrorReason_UNKNOWN_ERROR CartServiceErrorReason = 0
)

// Enum value maps for CartServiceErrorReason.
var (
	CartServiceErrorReason_name = map[int32]string{
		0: "UNKNOWN_ERROR",
	}
	CartServiceErrorReason_value = map[string]int32{
		"UNKNOWN_ERROR": 0,
	}
)

func (x CartServiceErrorReason) Enum() *CartServiceErrorReason {
	p := new(CartServiceErrorReason)
	*p = x
	return p
}

func (x CartServiceErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CartServiceErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_cart_service_v1_cart_error_proto_enumTypes[0].Descriptor()
}

func (CartServiceErrorReason) Type() protoreflect.EnumType {
	return &file_cart_service_v1_cart_error_proto_enumTypes[0]
}

func (x CartServiceErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CartServiceErrorReason.Descriptor instead.
func (CartServiceErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_cart_service_v1_cart_error_proto_rawDescGZIP(), []int{0}
}

var File_cart_service_v1_cart_error_proto protoreflect.FileDescriptor

const file_cart_service_v1_cart_error_proto_rawDesc = "" +
	"\n" +
	" cart/service/v1/cart_error.proto\x12\x0fcart.service.v1\x1a\x13errors/errors.proto*1\n" +
	"\x16CartServiceErrorReason\x12\x11\n" +
	"\rUNKNOWN_ERROR\x10\x00\x1a\x04\xa0E\xf4\x03B\xc4\x01\n" +
	"\x13com.cart.service.v1B\x0eCartErrorProtoP\x01Z?tlgitea.com/pingtai/gopkg/api/_gen/go/cart/service/v1;servicev1\xa2\x02\x03CSX\xaa\x02\x0fCart.Service.V1\xca\x02\x0fCart\\Service\\V1\xe2\x02\x1bCart\\Service\\V1\\GPBMetadata\xea\x02\x11Cart::Service::V1b\x06proto3"

var (
	file_cart_service_v1_cart_error_proto_rawDescOnce sync.Once
	file_cart_service_v1_cart_error_proto_rawDescData []byte
)

func file_cart_service_v1_cart_error_proto_rawDescGZIP() []byte {
	file_cart_service_v1_cart_error_proto_rawDescOnce.Do(func() {
		file_cart_service_v1_cart_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cart_service_v1_cart_error_proto_rawDesc), len(file_cart_service_v1_cart_error_proto_rawDesc)))
	})
	return file_cart_service_v1_cart_error_proto_rawDescData
}

var file_cart_service_v1_cart_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cart_service_v1_cart_error_proto_goTypes = []any{
	(CartServiceErrorReason)(0), // 0: cart.service.v1.CartServiceErrorReason
}
var file_cart_service_v1_cart_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cart_service_v1_cart_error_proto_init() }
func file_cart_service_v1_cart_error_proto_init() {
	if File_cart_service_v1_cart_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cart_service_v1_cart_error_proto_rawDesc), len(file_cart_service_v1_cart_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cart_service_v1_cart_error_proto_goTypes,
		DependencyIndexes: file_cart_service_v1_cart_error_proto_depIdxs,
		EnumInfos:         file_cart_service_v1_cart_error_proto_enumTypes,
	}.Build()
	File_cart_service_v1_cart_error_proto = out.File
	file_cart_service_v1_cart_error_proto_goTypes = nil
	file_cart_service_v1_cart_error_proto_depIdxs = nil
}
