// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: catalog/service/v1/catalog.proto

package servicev1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListBeerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNum       int64                  `protobuf:"varint,1,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBeerReq) Reset() {
	*x = ListBeerReq{}
	mi := &file_catalog_service_v1_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBeerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBeerReq) ProtoMessage() {}

func (x *ListBeerReq) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_service_v1_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBeerReq.ProtoReflect.Descriptor instead.
func (*ListBeerReq) Descriptor() ([]byte, []int) {
	return file_catalog_service_v1_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *ListBeerReq) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *ListBeerReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListBeerNextTokenReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum number of books to return. The service may return fewer than
	// this value.
	// If unspecified, at most 50 books will be returned.
	// The maximum value is 1000; values above 1000 will be coerced to 1000.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// A page token, received from a previous `ListBooks` call.
	// Provide this to retrieve the subsequent page.
	//
	// When paginating, all other parameters provided to `ListBooks` must match
	// the call that provided the page token.
	PageToken     string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBeerNextTokenReq) Reset() {
	*x = ListBeerNextTokenReq{}
	mi := &file_catalog_service_v1_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBeerNextTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBeerNextTokenReq) ProtoMessage() {}

func (x *ListBeerNextTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_service_v1_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBeerNextTokenReq.ProtoReflect.Descriptor instead.
func (*ListBeerNextTokenReq) Descriptor() ([]byte, []int) {
	return file_catalog_service_v1_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *ListBeerNextTokenReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListBeerNextTokenReq) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListBeerReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ListBeerReply_Beer  `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBeerReply) Reset() {
	*x = ListBeerReply{}
	mi := &file_catalog_service_v1_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBeerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBeerReply) ProtoMessage() {}

func (x *ListBeerReply) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_service_v1_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBeerReply.ProtoReflect.Descriptor instead.
func (*ListBeerReply) Descriptor() ([]byte, []int) {
	return file_catalog_service_v1_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *ListBeerReply) GetResults() []*ListBeerReply_Beer {
	if x != nil {
		return x.Results
	}
	return nil
}

type ListBeerReplyNextToken struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Results       []*ListBeerReplyNextToken_Beer `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	NextPageToken string                         `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBeerReplyNextToken) Reset() {
	*x = ListBeerReplyNextToken{}
	mi := &file_catalog_service_v1_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBeerReplyNextToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBeerReplyNextToken) ProtoMessage() {}

func (x *ListBeerReplyNextToken) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_service_v1_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBeerReplyNextToken.ProtoReflect.Descriptor instead.
func (*ListBeerReplyNextToken) Descriptor() ([]byte, []int) {
	return file_catalog_service_v1_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *ListBeerReplyNextToken) GetResults() []*ListBeerReplyNextToken_Beer {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ListBeerReplyNextToken) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CreateBeerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Count         int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Image         []*CreateBeerReq_Image `protobuf:"bytes,4,rep,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBeerReq) Reset() {
	*x = CreateBeerReq{}
	mi := &file_catalog_service_v1_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBeerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBeerReq) ProtoMessage() {}

func (x *CreateBeerReq) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_service_v1_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBeerReq.ProtoReflect.Descriptor instead.
func (*CreateBeerReq) Descriptor() ([]byte, []int) {
	return file_catalog_service_v1_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *CreateBeerReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateBeerReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateBeerReq) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *CreateBeerReq) GetImage() []*CreateBeerReq_Image {
	if x != nil {
		return x.Image
	}
	return nil
}

type CreateBeerReply struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Id            int64                    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Count         int64                    `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Image         []*CreateBeerReply_Image `protobuf:"bytes,5,rep,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBeerReply) Reset() {
	*x = CreateBeerReply{}
	mi := &file_catalog_service_v1_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBeerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBeerReply) ProtoMessage() {}

func (x *CreateBeerReply) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_service_v1_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBeerReply.ProtoReflect.Descriptor instead.
func (*CreateBeerReply) Descriptor() ([]byte, []int) {
	return file_catalog_service_v1_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *CreateBeerReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateBeerReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateBeerReply) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateBeerReply) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *CreateBeerReply) GetImage() []*CreateBeerReply_Image {
	if x != nil {
		return x.Image
	}
	return nil
}

type GetBeerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBeerReq) Reset() {
	*x = GetBeerReq{}
	mi := &file_catalog_service_v1_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBeerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBeerReq) ProtoMessage() {}

func (x *GetBeerReq) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_service_v1_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBeerReq.ProtoReflect.Descriptor instead.
func (*GetBeerReq) Descriptor() ([]byte, []int) {
	return file_catalog_service_v1_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *GetBeerReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetBeerReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Count         int64                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Image         []*GetBeerReply_Image  `protobuf:"bytes,5,rep,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBeerReply) Reset() {
	*x = GetBeerReply{}
	mi := &file_catalog_service_v1_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBeerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBeerReply) ProtoMessage() {}

func (x *GetBeerReply) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_service_v1_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBeerReply.ProtoReflect.Descriptor instead.
func (*GetBeerReply) Descriptor() ([]byte, []int) {
	return file_catalog_service_v1_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *GetBeerReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetBeerReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetBeerReply) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetBeerReply) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetBeerReply) GetImage() []*GetBeerReply_Image {
	if x != nil {
		return x.Image
	}
	return nil
}

type UpdateBeerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Count         int64                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Image         []*UpdateBeerReq_Image `protobuf:"bytes,5,rep,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBeerReq) Reset() {
	*x = UpdateBeerReq{}
	mi := &file_catalog_service_v1_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBeerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBeerReq) ProtoMessage() {}

func (x *UpdateBeerReq) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_service_v1_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBeerReq.ProtoReflect.Descriptor instead.
func (*UpdateBeerReq) Descriptor() ([]byte, []int) {
	return file_catalog_service_v1_catalog_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateBeerReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateBeerReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateBeerReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateBeerReq) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *UpdateBeerReq) GetImage() []*UpdateBeerReq_Image {
	if x != nil {
		return x.Image
	}
	return nil
}

type UpdateBeerReply struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Id            int64                    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Count         int64                    `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Image         []*UpdateBeerReply_Image `protobuf:"bytes,5,rep,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBeerReply) Reset() {
	*x = UpdateBeerReply{}
	mi := &file_catalog_service_v1_catalog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBeerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBeerReply) ProtoMessage() {}

func (x *UpdateBeerReply) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_service_v1_catalog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBeerReply.ProtoReflect.Descriptor instead.
func (*UpdateBeerReply) Descriptor() ([]byte, []int) {
	return file_catalog_service_v1_catalog_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateBeerReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateBeerReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateBeerReply) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateBeerReply) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *UpdateBeerReply) GetImage() []*UpdateBeerReply_Image {
	if x != nil {
		return x.Image
	}
	return nil
}

type DeleteBeerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBeerReq) Reset() {
	*x = DeleteBeerReq{}
	mi := &file_catalog_service_v1_catalog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBeerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBeerReq) ProtoMessage() {}

func (x *DeleteBeerReq) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_service_v1_catalog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBeerReq.ProtoReflect.Descriptor instead.
func (*DeleteBeerReq) Descriptor() ([]byte, []int) {
	return file_catalog_service_v1_catalog_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteBeerReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteBeerReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBeerReply) Reset() {
	*x = DeleteBeerReply{}
	mi := &file_catalog_service_v1_catalog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBeerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBeerReply) ProtoMessage() {}

func (x *DeleteBeerReply) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_service_v1_catalog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBeerReply.ProtoReflect.Descriptor instead.
func (*DeleteBeerReply) Descriptor() ([]byte, []int) {
	return file_catalog_service_v1_catalog_proto_rawDescGZIP(), []int{11}
}

type ListBeerReply_Beer struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Id            int64                       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                      `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Count         int64                       `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Image         []*ListBeerReply_Beer_Image `protobuf:"bytes,5,rep,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBeerReply_Beer) Reset() {
	*x = ListBeerReply_Beer{}
	mi := &file_catalog_service_v1_catalog_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBeerReply_Beer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBeerReply_Beer) ProtoMessage() {}

func (x *ListBeerReply_Beer) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_service_v1_catalog_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBeerReply_Beer.ProtoReflect.Descriptor instead.
func (*ListBeerReply_Beer) Descriptor() ([]byte, []int) {
	return file_catalog_service_v1_catalog_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ListBeerReply_Beer) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListBeerReply_Beer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListBeerReply_Beer) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ListBeerReply_Beer) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ListBeerReply_Beer) GetImage() []*ListBeerReply_Beer_Image {
	if x != nil {
		return x.Image
	}
	return nil
}

type ListBeerReply_Beer_Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBeerReply_Beer_Image) Reset() {
	*x = ListBeerReply_Beer_Image{}
	mi := &file_catalog_service_v1_catalog_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBeerReply_Beer_Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBeerReply_Beer_Image) ProtoMessage() {}

func (x *ListBeerReply_Beer_Image) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_service_v1_catalog_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBeerReply_Beer_Image.ProtoReflect.Descriptor instead.
func (*ListBeerReply_Beer_Image) Descriptor() ([]byte, []int) {
	return file_catalog_service_v1_catalog_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *ListBeerReply_Beer_Image) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ListBeerReplyNextToken_Beer struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Id            int64                                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                               `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Count         int64                                `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Image         []*ListBeerReplyNextToken_Beer_Image `protobuf:"bytes,5,rep,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBeerReplyNextToken_Beer) Reset() {
	*x = ListBeerReplyNextToken_Beer{}
	mi := &file_catalog_service_v1_catalog_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBeerReplyNextToken_Beer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBeerReplyNextToken_Beer) ProtoMessage() {}

func (x *ListBeerReplyNextToken_Beer) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_service_v1_catalog_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBeerReplyNextToken_Beer.ProtoReflect.Descriptor instead.
func (*ListBeerReplyNextToken_Beer) Descriptor() ([]byte, []int) {
	return file_catalog_service_v1_catalog_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ListBeerReplyNextToken_Beer) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListBeerReplyNextToken_Beer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListBeerReplyNextToken_Beer) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ListBeerReplyNextToken_Beer) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ListBeerReplyNextToken_Beer) GetImage() []*ListBeerReplyNextToken_Beer_Image {
	if x != nil {
		return x.Image
	}
	return nil
}

type ListBeerReplyNextToken_Beer_Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBeerReplyNextToken_Beer_Image) Reset() {
	*x = ListBeerReplyNextToken_Beer_Image{}
	mi := &file_catalog_service_v1_catalog_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBeerReplyNextToken_Beer_Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBeerReplyNextToken_Beer_Image) ProtoMessage() {}

func (x *ListBeerReplyNextToken_Beer_Image) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_service_v1_catalog_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBeerReplyNextToken_Beer_Image.ProtoReflect.Descriptor instead.
func (*ListBeerReplyNextToken_Beer_Image) Descriptor() ([]byte, []int) {
	return file_catalog_service_v1_catalog_proto_rawDescGZIP(), []int{3, 0, 0}
}

func (x *ListBeerReplyNextToken_Beer_Image) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CreateBeerReq_Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBeerReq_Image) Reset() {
	*x = CreateBeerReq_Image{}
	mi := &file_catalog_service_v1_catalog_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBeerReq_Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBeerReq_Image) ProtoMessage() {}

func (x *CreateBeerReq_Image) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_service_v1_catalog_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBeerReq_Image.ProtoReflect.Descriptor instead.
func (*CreateBeerReq_Image) Descriptor() ([]byte, []int) {
	return file_catalog_service_v1_catalog_proto_rawDescGZIP(), []int{4, 0}
}

func (x *CreateBeerReq_Image) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CreateBeerReply_Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBeerReply_Image) Reset() {
	*x = CreateBeerReply_Image{}
	mi := &file_catalog_service_v1_catalog_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBeerReply_Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBeerReply_Image) ProtoMessage() {}

func (x *CreateBeerReply_Image) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_service_v1_catalog_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBeerReply_Image.ProtoReflect.Descriptor instead.
func (*CreateBeerReply_Image) Descriptor() ([]byte, []int) {
	return file_catalog_service_v1_catalog_proto_rawDescGZIP(), []int{5, 0}
}

func (x *CreateBeerReply_Image) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetBeerReply_Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBeerReply_Image) Reset() {
	*x = GetBeerReply_Image{}
	mi := &file_catalog_service_v1_catalog_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBeerReply_Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBeerReply_Image) ProtoMessage() {}

func (x *GetBeerReply_Image) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_service_v1_catalog_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBeerReply_Image.ProtoReflect.Descriptor instead.
func (*GetBeerReply_Image) Descriptor() ([]byte, []int) {
	return file_catalog_service_v1_catalog_proto_rawDescGZIP(), []int{7, 0}
}

func (x *GetBeerReply_Image) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type UpdateBeerReq_Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBeerReq_Image) Reset() {
	*x = UpdateBeerReq_Image{}
	mi := &file_catalog_service_v1_catalog_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBeerReq_Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBeerReq_Image) ProtoMessage() {}

func (x *UpdateBeerReq_Image) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_service_v1_catalog_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBeerReq_Image.ProtoReflect.Descriptor instead.
func (*UpdateBeerReq_Image) Descriptor() ([]byte, []int) {
	return file_catalog_service_v1_catalog_proto_rawDescGZIP(), []int{8, 0}
}

func (x *UpdateBeerReq_Image) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type UpdateBeerReply_Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBeerReply_Image) Reset() {
	*x = UpdateBeerReply_Image{}
	mi := &file_catalog_service_v1_catalog_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBeerReply_Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBeerReply_Image) ProtoMessage() {}

func (x *UpdateBeerReply_Image) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_service_v1_catalog_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBeerReply_Image.ProtoReflect.Descriptor instead.
func (*UpdateBeerReply_Image) Descriptor() ([]byte, []int) {
	return file_catalog_service_v1_catalog_proto_rawDescGZIP(), []int{9, 0}
}

func (x *UpdateBeerReply_Image) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_catalog_service_v1_catalog_proto protoreflect.FileDescriptor

const file_catalog_service_v1_catalog_proto_rawDesc = "" +
	"\n" +
	" catalog/service/v1/catalog.proto\x12\x12catalog.service.v1\x1a\x1cgoogle/api/annotations.proto\"E\n" +
	"\vListBeerReq\x12\x19\n" +
	"\bpage_num\x18\x01 \x01(\x03R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\"R\n" +
	"\x14listBeerNextTokenReq\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"\x95\x02\n" +
	"\rListBeerReply\x12@\n" +
	"\aresults\x18\x01 \x03(\v2&.catalog.service.v1.ListBeerReply.BeerR\aresults\x1a\xc1\x01\n" +
	"\x04Beer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x03R\x05count\x12B\n" +
	"\x05image\x18\x05 \x03(\v2,.catalog.service.v1.ListBeerReply.Beer.ImageR\x05image\x1a\x19\n" +
	"\x05Image\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\xd8\x02\n" +
	"\x16ListBeerReplyNextToken\x12I\n" +
	"\aresults\x18\x01 \x03(\v2/.catalog.service.v1.ListBeerReplyNextToken.BeerR\aresults\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x1a\xca\x01\n" +
	"\x04Beer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x03R\x05count\x12K\n" +
	"\x05image\x18\x05 \x03(\v25.catalog.service.v1.ListBeerReplyNextToken.Beer.ImageR\x05image\x1a\x19\n" +
	"\x05Image\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\xb5\x01\n" +
	"\rCreateBeerReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\x12=\n" +
	"\x05image\x18\x04 \x03(\v2'.catalog.service.v1.CreateBeerReq.ImageR\x05image\x1a\x19\n" +
	"\x05Image\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\xc9\x01\n" +
	"\x0fCreateBeerReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x03R\x05count\x12?\n" +
	"\x05image\x18\x05 \x03(\v2).catalog.service.v1.CreateBeerReply.ImageR\x05image\x1a\x19\n" +
	"\x05Image\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x1c\n" +
	"\n" +
	"GetBeerReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xc3\x01\n" +
	"\fGetBeerReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x03R\x05count\x12<\n" +
	"\x05image\x18\x05 \x03(\v2&.catalog.service.v1.GetBeerReply.ImageR\x05image\x1a\x19\n" +
	"\x05Image\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\xc5\x01\n" +
	"\rUpdateBeerReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x03R\x05count\x12=\n" +
	"\x05image\x18\x05 \x03(\v2'.catalog.service.v1.UpdateBeerReq.ImageR\x05image\x1a\x19\n" +
	"\x05Image\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\xc9\x01\n" +
	"\x0fUpdateBeerReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x03R\x05count\x12?\n" +
	"\x05image\x18\x05 \x03(\v2).catalog.service.v1.UpdateBeerReply.ImageR\x05image\x1a\x19\n" +
	"\x05Image\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x1f\n" +
	"\rDeleteBeerReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x11\n" +
	"\x0fDeleteBeerReply2\x9f\x04\n" +
	"\aCatalog\x12P\n" +
	"\bListBeer\x12\x1f.catalog.service.v1.ListBeerReq\x1a!.catalog.service.v1.ListBeerReply\"\x00\x12k\n" +
	"\x11ListBeerNextToken\x12(.catalog.service.v1.listBeerNextTokenReq\x1a*.catalog.service.v1.ListBeerReplyNextToken\"\x00\x12V\n" +
	"\n" +
	"CreateBeer\x12!.catalog.service.v1.CreateBeerReq\x1a#.catalog.service.v1.CreateBeerReply\"\x00\x12M\n" +
	"\aGetBeer\x12\x1e.catalog.service.v1.GetBeerReq\x1a .catalog.service.v1.GetBeerReply\"\x00\x12V\n" +
	"\n" +
	"UpdateBeer\x12!.catalog.service.v1.UpdateBeerReq\x1a#.catalog.service.v1.UpdateBeerReply\"\x00\x12V\n" +
	"\n" +
	"DeleteBeer\x12!.catalog.service.v1.DeleteBeerReq\x1a#.catalog.service.v1.DeleteBeerReply\"\x00B\xd4\x01\n" +
	"\x16com.catalog.service.v1B\fCatalogProtoP\x01ZBtlgitea.com/pingtai/gopkg/api/_gen/go/catalog/service/v1;servicev1\xa2\x02\x03CSX\xaa\x02\x12Catalog.Service.V1\xca\x02\x12Catalog\\Service\\V1\xe2\x02\x1eCatalog\\Service\\V1\\GPBMetadata\xea\x02\x14Catalog::Service::V1b\x06proto3"

var (
	file_catalog_service_v1_catalog_proto_rawDescOnce sync.Once
	file_catalog_service_v1_catalog_proto_rawDescData []byte
)

func file_catalog_service_v1_catalog_proto_rawDescGZIP() []byte {
	file_catalog_service_v1_catalog_proto_rawDescOnce.Do(func() {
		file_catalog_service_v1_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_service_v1_catalog_proto_rawDesc), len(file_catalog_service_v1_catalog_proto_rawDesc)))
	})
	return file_catalog_service_v1_catalog_proto_rawDescData
}

var file_catalog_service_v1_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_catalog_service_v1_catalog_proto_goTypes = []any{
	(*ListBeerReq)(nil),                       // 0: catalog.service.v1.ListBeerReq
	(*ListBeerNextTokenReq)(nil),              // 1: catalog.service.v1.listBeerNextTokenReq
	(*ListBeerReply)(nil),                     // 2: catalog.service.v1.ListBeerReply
	(*ListBeerReplyNextToken)(nil),            // 3: catalog.service.v1.ListBeerReplyNextToken
	(*CreateBeerReq)(nil),                     // 4: catalog.service.v1.CreateBeerReq
	(*CreateBeerReply)(nil),                   // 5: catalog.service.v1.CreateBeerReply
	(*GetBeerReq)(nil),                        // 6: catalog.service.v1.GetBeerReq
	(*GetBeerReply)(nil),                      // 7: catalog.service.v1.GetBeerReply
	(*UpdateBeerReq)(nil),                     // 8: catalog.service.v1.UpdateBeerReq
	(*UpdateBeerReply)(nil),                   // 9: catalog.service.v1.UpdateBeerReply
	(*DeleteBeerReq)(nil),                     // 10: catalog.service.v1.DeleteBeerReq
	(*DeleteBeerReply)(nil),                   // 11: catalog.service.v1.DeleteBeerReply
	(*ListBeerReply_Beer)(nil),                // 12: catalog.service.v1.ListBeerReply.Beer
	(*ListBeerReply_Beer_Image)(nil),          // 13: catalog.service.v1.ListBeerReply.Beer.Image
	(*ListBeerReplyNextToken_Beer)(nil),       // 14: catalog.service.v1.ListBeerReplyNextToken.Beer
	(*ListBeerReplyNextToken_Beer_Image)(nil), // 15: catalog.service.v1.ListBeerReplyNextToken.Beer.Image
	(*CreateBeerReq_Image)(nil),               // 16: catalog.service.v1.CreateBeerReq.Image
	(*CreateBeerReply_Image)(nil),             // 17: catalog.service.v1.CreateBeerReply.Image
	(*GetBeerReply_Image)(nil),                // 18: catalog.service.v1.GetBeerReply.Image
	(*UpdateBeerReq_Image)(nil),               // 19: catalog.service.v1.UpdateBeerReq.Image
	(*UpdateBeerReply_Image)(nil),             // 20: catalog.service.v1.UpdateBeerReply.Image
}
var file_catalog_service_v1_catalog_proto_depIdxs = []int32{
	12, // 0: catalog.service.v1.ListBeerReply.results:type_name -> catalog.service.v1.ListBeerReply.Beer
	14, // 1: catalog.service.v1.ListBeerReplyNextToken.results:type_name -> catalog.service.v1.ListBeerReplyNextToken.Beer
	16, // 2: catalog.service.v1.CreateBeerReq.image:type_name -> catalog.service.v1.CreateBeerReq.Image
	17, // 3: catalog.service.v1.CreateBeerReply.image:type_name -> catalog.service.v1.CreateBeerReply.Image
	18, // 4: catalog.service.v1.GetBeerReply.image:type_name -> catalog.service.v1.GetBeerReply.Image
	19, // 5: catalog.service.v1.UpdateBeerReq.image:type_name -> catalog.service.v1.UpdateBeerReq.Image
	20, // 6: catalog.service.v1.UpdateBeerReply.image:type_name -> catalog.service.v1.UpdateBeerReply.Image
	13, // 7: catalog.service.v1.ListBeerReply.Beer.image:type_name -> catalog.service.v1.ListBeerReply.Beer.Image
	15, // 8: catalog.service.v1.ListBeerReplyNextToken.Beer.image:type_name -> catalog.service.v1.ListBeerReplyNextToken.Beer.Image
	0,  // 9: catalog.service.v1.Catalog.ListBeer:input_type -> catalog.service.v1.ListBeerReq
	1,  // 10: catalog.service.v1.Catalog.ListBeerNextToken:input_type -> catalog.service.v1.listBeerNextTokenReq
	4,  // 11: catalog.service.v1.Catalog.CreateBeer:input_type -> catalog.service.v1.CreateBeerReq
	6,  // 12: catalog.service.v1.Catalog.GetBeer:input_type -> catalog.service.v1.GetBeerReq
	8,  // 13: catalog.service.v1.Catalog.UpdateBeer:input_type -> catalog.service.v1.UpdateBeerReq
	10, // 14: catalog.service.v1.Catalog.DeleteBeer:input_type -> catalog.service.v1.DeleteBeerReq
	2,  // 15: catalog.service.v1.Catalog.ListBeer:output_type -> catalog.service.v1.ListBeerReply
	3,  // 16: catalog.service.v1.Catalog.ListBeerNextToken:output_type -> catalog.service.v1.ListBeerReplyNextToken
	5,  // 17: catalog.service.v1.Catalog.CreateBeer:output_type -> catalog.service.v1.CreateBeerReply
	7,  // 18: catalog.service.v1.Catalog.GetBeer:output_type -> catalog.service.v1.GetBeerReply
	9,  // 19: catalog.service.v1.Catalog.UpdateBeer:output_type -> catalog.service.v1.UpdateBeerReply
	11, // 20: catalog.service.v1.Catalog.DeleteBeer:output_type -> catalog.service.v1.DeleteBeerReply
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_catalog_service_v1_catalog_proto_init() }
func file_catalog_service_v1_catalog_proto_init() {
	if File_catalog_service_v1_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_service_v1_catalog_proto_rawDesc), len(file_catalog_service_v1_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_catalog_service_v1_catalog_proto_goTypes,
		DependencyIndexes: file_catalog_service_v1_catalog_proto_depIdxs,
		MessageInfos:      file_catalog_service_v1_catalog_proto_msgTypes,
	}.Build()
	File_catalog_service_v1_catalog_proto = out.File
	file_catalog_service_v1_catalog_proto_goTypes = nil
	file_catalog_service_v1_catalog_proto_depIdxs = nil
}
