// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: catalog/service/v1/catalog_error.proto

package servicev1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CatalogServiceErrorReason int32

const (
	CatalogServiceErrorReason_UNKNOWN_ERROR CatalogServiceErrorReason = 0
)

// Enum value maps for CatalogServiceErrorReason.
var (
	CatalogServiceErrorReason_name = map[int32]string{
		0: "UNKNOWN_ERROR",
	}
	CatalogServiceErrorReason_value = map[string]int32{
		"UNKNOWN_ERROR": 0,
	}
)

func (x CatalogServiceErrorReason) Enum() *CatalogServiceErrorReason {
	p := new(CatalogServiceErrorReason)
	*p = x
	return p
}

func (x CatalogServiceErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CatalogServiceErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_catalog_service_v1_catalog_error_proto_enumTypes[0].Descriptor()
}

func (CatalogServiceErrorReason) Type() protoreflect.EnumType {
	return &file_catalog_service_v1_catalog_error_proto_enumTypes[0]
}

func (x CatalogServiceErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CatalogServiceErrorReason.Descriptor instead.
func (CatalogServiceErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_catalog_service_v1_catalog_error_proto_rawDescGZIP(), []int{0}
}

var File_catalog_service_v1_catalog_error_proto protoreflect.FileDescriptor

const file_catalog_service_v1_catalog_error_proto_rawDesc = "" +
	"\n" +
	"&catalog/service/v1/catalog_error.proto\x12\x12catalog.service.v1\x1a\x13errors/errors.proto*4\n" +
	"\x19CatalogServiceErrorReason\x12\x11\n" +
	"\rUNKNOWN_ERROR\x10\x00\x1a\x04\xa0E\xf4\x03B\xd9\x01\n" +
	"\x16com.catalog.service.v1B\x11CatalogErrorProtoP\x01ZBtlgitea.com/pingtai/gopkg/api/_gen/go/catalog/service/v1;servicev1\xa2\x02\x03CSX\xaa\x02\x12Catalog.Service.V1\xca\x02\x12Catalog\\Service\\V1\xe2\x02\x1eCatalog\\Service\\V1\\GPBMetadata\xea\x02\x14Catalog::Service::V1b\x06proto3"

var (
	file_catalog_service_v1_catalog_error_proto_rawDescOnce sync.Once
	file_catalog_service_v1_catalog_error_proto_rawDescData []byte
)

func file_catalog_service_v1_catalog_error_proto_rawDescGZIP() []byte {
	file_catalog_service_v1_catalog_error_proto_rawDescOnce.Do(func() {
		file_catalog_service_v1_catalog_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_service_v1_catalog_error_proto_rawDesc), len(file_catalog_service_v1_catalog_error_proto_rawDesc)))
	})
	return file_catalog_service_v1_catalog_error_proto_rawDescData
}

var file_catalog_service_v1_catalog_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_catalog_service_v1_catalog_error_proto_goTypes = []any{
	(CatalogServiceErrorReason)(0), // 0: catalog.service.v1.CatalogServiceErrorReason
}
var file_catalog_service_v1_catalog_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_catalog_service_v1_catalog_error_proto_init() }
func file_catalog_service_v1_catalog_error_proto_init() {
	if File_catalog_service_v1_catalog_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_service_v1_catalog_error_proto_rawDesc), len(file_catalog_service_v1_catalog_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_service_v1_catalog_error_proto_goTypes,
		DependencyIndexes: file_catalog_service_v1_catalog_error_proto_depIdxs,
		EnumInfos:         file_catalog_service_v1_catalog_error_proto_enumTypes,
	}.Build()
	File_catalog_service_v1_catalog_error_proto = out.File
	file_catalog_service_v1_catalog_error_proto_goTypes = nil
	file_catalog_service_v1_catalog_error_proto_depIdxs = nil
}
