// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: payment/service/v1/payment.proto

package servicev1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentAuthReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentAuthReq) Reset() {
	*x = PaymentAuthReq{}
	mi := &file_payment_service_v1_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentAuthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentAuthReq) ProtoMessage() {}

func (x *PaymentAuthReq) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_v1_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentAuthReq.ProtoReflect.Descriptor instead.
func (*PaymentAuthReq) Descriptor() ([]byte, []int) {
	return file_payment_service_v1_payment_proto_rawDescGZIP(), []int{0}
}

type PaymentAuthReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentAuthReply) Reset() {
	*x = PaymentAuthReply{}
	mi := &file_payment_service_v1_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentAuthReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentAuthReply) ProtoMessage() {}

func (x *PaymentAuthReply) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_v1_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentAuthReply.ProtoReflect.Descriptor instead.
func (*PaymentAuthReply) Descriptor() ([]byte, []int) {
	return file_payment_service_v1_payment_proto_rawDescGZIP(), []int{1}
}

var File_payment_service_v1_payment_proto protoreflect.FileDescriptor

const file_payment_service_v1_payment_proto_rawDesc = "" +
	"\n" +
	" payment/service/v1/payment.proto\x12\x12payment.service.v1\x1a\x1cgoogle/api/annotations.proto\"\x10\n" +
	"\x0ePaymentAuthReq\"\x12\n" +
	"\x10PaymentAuthReply2d\n" +
	"\aPayment\x12Y\n" +
	"\vPaymentAuth\x12\".payment.service.v1.PaymentAuthReq\x1a$.payment.service.v1.PaymentAuthReply\"\x00B\xd4\x01\n" +
	"\x16com.payment.service.v1B\fPaymentProtoP\x01ZBtlgitea.com/pingtai/gopkg/api/_gen/go/payment/service/v1;servicev1\xa2\x02\x03PSX\xaa\x02\x12Payment.Service.V1\xca\x02\x12Payment\\Service\\V1\xe2\x02\x1ePayment\\Service\\V1\\GPBMetadata\xea\x02\x14Payment::Service::V1b\x06proto3"

var (
	file_payment_service_v1_payment_proto_rawDescOnce sync.Once
	file_payment_service_v1_payment_proto_rawDescData []byte
)

func file_payment_service_v1_payment_proto_rawDescGZIP() []byte {
	file_payment_service_v1_payment_proto_rawDescOnce.Do(func() {
		file_payment_service_v1_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_service_v1_payment_proto_rawDesc), len(file_payment_service_v1_payment_proto_rawDesc)))
	})
	return file_payment_service_v1_payment_proto_rawDescData
}

var file_payment_service_v1_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_payment_service_v1_payment_proto_goTypes = []any{
	(*PaymentAuthReq)(nil),   // 0: payment.service.v1.PaymentAuthReq
	(*PaymentAuthReply)(nil), // 1: payment.service.v1.PaymentAuthReply
}
var file_payment_service_v1_payment_proto_depIdxs = []int32{
	0, // 0: payment.service.v1.Payment.PaymentAuth:input_type -> payment.service.v1.PaymentAuthReq
	1, // 1: payment.service.v1.Payment.PaymentAuth:output_type -> payment.service.v1.PaymentAuthReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_payment_service_v1_payment_proto_init() }
func file_payment_service_v1_payment_proto_init() {
	if File_payment_service_v1_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_service_v1_payment_proto_rawDesc), len(file_payment_service_v1_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_service_v1_payment_proto_goTypes,
		DependencyIndexes: file_payment_service_v1_payment_proto_depIdxs,
		MessageInfos:      file_payment_service_v1_payment_proto_msgTypes,
	}.Build()
	File_payment_service_v1_payment_proto = out.File
	file_payment_service_v1_payment_proto_goTypes = nil
	file_payment_service_v1_payment_proto_depIdxs = nil
}
