// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: payment/service/v1/payment_error.proto

package servicev1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentServiceErrorReason int32

const (
	PaymentServiceErrorReason_UNKNOWN_ERROR PaymentServiceErrorReason = 0
)

// Enum value maps for PaymentServiceErrorReason.
var (
	PaymentServiceErrorReason_name = map[int32]string{
		0: "UNKNOWN_ERROR",
	}
	PaymentServiceErrorReason_value = map[string]int32{
		"UNKNOWN_ERROR": 0,
	}
)

func (x PaymentServiceErrorReason) Enum() *PaymentServiceErrorReason {
	p := new(PaymentServiceErrorReason)
	*p = x
	return p
}

func (x PaymentServiceErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentServiceErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_service_v1_payment_error_proto_enumTypes[0].Descriptor()
}

func (PaymentServiceErrorReason) Type() protoreflect.EnumType {
	return &file_payment_service_v1_payment_error_proto_enumTypes[0]
}

func (x PaymentServiceErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentServiceErrorReason.Descriptor instead.
func (PaymentServiceErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_payment_service_v1_payment_error_proto_rawDescGZIP(), []int{0}
}

var File_payment_service_v1_payment_error_proto protoreflect.FileDescriptor

const file_payment_service_v1_payment_error_proto_rawDesc = "" +
	"\n" +
	"&payment/service/v1/payment_error.proto\x12\x12payment.service.v1\x1a\x13errors/errors.proto*4\n" +
	"\x19PaymentServiceErrorReason\x12\x11\n" +
	"\rUNKNOWN_ERROR\x10\x00\x1a\x04\xa0E\xf4\x03B\xd9\x01\n" +
	"\x16com.payment.service.v1B\x11PaymentErrorProtoP\x01ZBtlgitea.com/pingtai/gopkg/api/_gen/go/payment/service/v1;servicev1\xa2\x02\x03PSX\xaa\x02\x12Payment.Service.V1\xca\x02\x12Payment\\Service\\V1\xe2\x02\x1ePayment\\Service\\V1\\GPBMetadata\xea\x02\x14Payment::Service::V1b\x06proto3"

var (
	file_payment_service_v1_payment_error_proto_rawDescOnce sync.Once
	file_payment_service_v1_payment_error_proto_rawDescData []byte
)

func file_payment_service_v1_payment_error_proto_rawDescGZIP() []byte {
	file_payment_service_v1_payment_error_proto_rawDescOnce.Do(func() {
		file_payment_service_v1_payment_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_service_v1_payment_error_proto_rawDesc), len(file_payment_service_v1_payment_error_proto_rawDesc)))
	})
	return file_payment_service_v1_payment_error_proto_rawDescData
}

var file_payment_service_v1_payment_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_payment_service_v1_payment_error_proto_goTypes = []any{
	(PaymentServiceErrorReason)(0), // 0: payment.service.v1.PaymentServiceErrorReason
}
var file_payment_service_v1_payment_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_payment_service_v1_payment_error_proto_init() }
func file_payment_service_v1_payment_error_proto_init() {
	if File_payment_service_v1_payment_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_service_v1_payment_error_proto_rawDesc), len(file_payment_service_v1_payment_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_payment_service_v1_payment_error_proto_goTypes,
		DependencyIndexes: file_payment_service_v1_payment_error_proto_depIdxs,
		EnumInfos:         file_payment_service_v1_payment_error_proto_enumTypes,
	}.Build()
	File_payment_service_v1_payment_error_proto = out.File
	file_payment_service_v1_payment_error_proto_goTypes = nil
	file_payment_service_v1_payment_error_proto_depIdxs = nil
}
