// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: shop/admin/v1/shop_admin.proto

package adminv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReply) Reset() {
	*x = RegisterReply{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReply) ProtoMessage() {}

func (x *RegisterReply) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReply.ProtoReflect.Descriptor instead.
func (*RegisterReply) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{2}
}

func (x *LoginReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{3}
}

func (x *LoginReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LogoutReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutReq) Reset() {
	*x = LogoutReq{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutReq) ProtoMessage() {}

func (x *LogoutReq) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutReq.ProtoReflect.Descriptor instead.
func (*LogoutReq) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{4}
}

type LogoutReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutReply) Reset() {
	*x = LogoutReply{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutReply) ProtoMessage() {}

func (x *LogoutReply) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutReply.ProtoReflect.Descriptor instead.
func (*LogoutReply) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{5}
}

type GetUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserReq) Reset() {
	*x = GetUserReq{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReq) ProtoMessage() {}

func (x *GetUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReq.ProtoReflect.Descriptor instead.
func (*GetUserReq) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserReply) Reset() {
	*x = GetUserReply{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReply) ProtoMessage() {}

func (x *GetUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReply.ProtoReflect.Descriptor instead.
func (*GetUserReply) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetUserReply) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ListUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserReq) Reset() {
	*x = ListUserReq{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserReq) ProtoMessage() {}

func (x *ListUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserReq.ProtoReflect.Descriptor instead.
func (*ListUserReq) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{8}
}

type ListUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserReply) Reset() {
	*x = ListUserReply{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserReply) ProtoMessage() {}

func (x *ListUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserReply.ProtoReflect.Descriptor instead.
func (*ListUserReply) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{9}
}

type CreateUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserReq) Reset() {
	*x = CreateUserReq{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserReq) ProtoMessage() {}

func (x *CreateUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserReq.ProtoReflect.Descriptor instead.
func (*CreateUserReq) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{10}
}

func (x *CreateUserReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreateUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserReply) Reset() {
	*x = CreateUserReply{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserReply) ProtoMessage() {}

func (x *CreateUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserReply.ProtoReflect.Descriptor instead.
func (*CreateUserReply) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{11}
}

func (x *CreateUserReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateUserReply) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type VerifyPasswordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPasswordReq) Reset() {
	*x = VerifyPasswordReq{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPasswordReq) ProtoMessage() {}

func (x *VerifyPasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPasswordReq.ProtoReflect.Descriptor instead.
func (*VerifyPasswordReq) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{12}
}

func (x *VerifyPasswordReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *VerifyPasswordReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type VerifyPasswordReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPasswordReply) Reset() {
	*x = VerifyPasswordReply{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPasswordReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPasswordReply) ProtoMessage() {}

func (x *VerifyPasswordReply) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPasswordReply.ProtoReflect.Descriptor instead.
func (*VerifyPasswordReply) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{13}
}

func (x *VerifyPasswordReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *VerifyPasswordReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListAddressReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAddressReq) Reset() {
	*x = ListAddressReq{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAddressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAddressReq) ProtoMessage() {}

func (x *ListAddressReq) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAddressReq.ProtoReflect.Descriptor instead.
func (*ListAddressReq) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{14}
}

func (x *ListAddressReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type ListAddressReply struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Results       []*ListAddressReply_Address `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAddressReply) Reset() {
	*x = ListAddressReply{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAddressReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAddressReply) ProtoMessage() {}

func (x *ListAddressReply) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAddressReply.ProtoReflect.Descriptor instead.
func (*ListAddressReply) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{15}
}

func (x *ListAddressReply) GetResults() []*ListAddressReply_Address {
	if x != nil {
		return x.Results
	}
	return nil
}

type CreateAddressReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mobile        string                 `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Country       string                 `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	City          string                 `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	Address       string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	PostCode      string                 `protobuf:"bytes,7,opt,name=post_code,json=postCode,proto3" json:"post_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAddressReq) Reset() {
	*x = CreateAddressReq{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAddressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAddressReq) ProtoMessage() {}

func (x *CreateAddressReq) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAddressReq.ProtoReflect.Descriptor instead.
func (*CreateAddressReq) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{16}
}

func (x *CreateAddressReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CreateAddressReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAddressReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *CreateAddressReq) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CreateAddressReq) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateAddressReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateAddressReq) GetPostCode() string {
	if x != nil {
		return x.PostCode
	}
	return ""
}

type CreateAddressReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mobile        string                 `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Country       string                 `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	City          string                 `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	Address       string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	PostCode      string                 `protobuf:"bytes,7,opt,name=post_code,json=postCode,proto3" json:"post_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAddressReply) Reset() {
	*x = CreateAddressReply{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAddressReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAddressReply) ProtoMessage() {}

func (x *CreateAddressReply) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAddressReply.ProtoReflect.Descriptor instead.
func (*CreateAddressReply) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{17}
}

func (x *CreateAddressReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateAddressReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAddressReply) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *CreateAddressReply) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CreateAddressReply) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateAddressReply) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateAddressReply) GetPostCode() string {
	if x != nil {
		return x.PostCode
	}
	return ""
}

type GetAddressReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressReq) Reset() {
	*x = GetAddressReq{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressReq) ProtoMessage() {}

func (x *GetAddressReq) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressReq.ProtoReflect.Descriptor instead.
func (*GetAddressReq) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{18}
}

func (x *GetAddressReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAddressReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mobile        string                 `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Country       string                 `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	City          string                 `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	Address       string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	PostCode      string                 `protobuf:"bytes,7,opt,name=post_code,json=postCode,proto3" json:"post_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressReply) Reset() {
	*x = GetAddressReply{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressReply) ProtoMessage() {}

func (x *GetAddressReply) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressReply.ProtoReflect.Descriptor instead.
func (*GetAddressReply) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{19}
}

func (x *GetAddressReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetAddressReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetAddressReply) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *GetAddressReply) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *GetAddressReply) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *GetAddressReply) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetAddressReply) GetPostCode() string {
	if x != nil {
		return x.PostCode
	}
	return ""
}

type ListCardReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCardReq) Reset() {
	*x = ListCardReq{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCardReq) ProtoMessage() {}

func (x *ListCardReq) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCardReq.ProtoReflect.Descriptor instead.
func (*ListCardReq) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{20}
}

func (x *ListCardReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type ListCardReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ListCardReply_Card  `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCardReply) Reset() {
	*x = ListCardReply{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCardReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCardReply) ProtoMessage() {}

func (x *ListCardReply) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCardReply.ProtoReflect.Descriptor instead.
func (*ListCardReply) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{21}
}

func (x *ListCardReply) GetResults() []*ListCardReply_Card {
	if x != nil {
		return x.Results
	}
	return nil
}

type CreateCardReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	CardNo        string                 `protobuf:"bytes,2,opt,name=card_no,json=cardNo,proto3" json:"card_no,omitempty"`
	Ccv           string                 `protobuf:"bytes,3,opt,name=ccv,proto3" json:"ccv,omitempty"`
	Expires       string                 `protobuf:"bytes,4,opt,name=expires,proto3" json:"expires,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCardReq) Reset() {
	*x = CreateCardReq{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCardReq) ProtoMessage() {}

func (x *CreateCardReq) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCardReq.ProtoReflect.Descriptor instead.
func (*CreateCardReq) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{22}
}

func (x *CreateCardReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CreateCardReq) GetCardNo() string {
	if x != nil {
		return x.CardNo
	}
	return ""
}

func (x *CreateCardReq) GetCcv() string {
	if x != nil {
		return x.Ccv
	}
	return ""
}

func (x *CreateCardReq) GetExpires() string {
	if x != nil {
		return x.Expires
	}
	return ""
}

type CreateCardReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCardReply) Reset() {
	*x = CreateCardReply{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCardReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCardReply) ProtoMessage() {}

func (x *CreateCardReply) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCardReply.ProtoReflect.Descriptor instead.
func (*CreateCardReply) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{23}
}

func (x *CreateCardReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetCardReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardReq) Reset() {
	*x = GetCardReq{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardReq) ProtoMessage() {}

func (x *GetCardReq) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardReq.ProtoReflect.Descriptor instead.
func (*GetCardReq) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{24}
}

func (x *GetCardReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetCardReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CardNo        string                 `protobuf:"bytes,2,opt,name=card_no,json=cardNo,proto3" json:"card_no,omitempty"`
	Ccv           string                 `protobuf:"bytes,3,opt,name=ccv,proto3" json:"ccv,omitempty"`
	Expires       string                 `protobuf:"bytes,4,opt,name=expires,proto3" json:"expires,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardReply) Reset() {
	*x = GetCardReply{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardReply) ProtoMessage() {}

func (x *GetCardReply) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardReply.ProtoReflect.Descriptor instead.
func (*GetCardReply) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{25}
}

func (x *GetCardReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetCardReply) GetCardNo() string {
	if x != nil {
		return x.CardNo
	}
	return ""
}

func (x *GetCardReply) GetCcv() string {
	if x != nil {
		return x.Ccv
	}
	return ""
}

func (x *GetCardReply) GetExpires() string {
	if x != nil {
		return x.Expires
	}
	return ""
}

type DeleteCardReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCardReq) Reset() {
	*x = DeleteCardReq{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCardReq) ProtoMessage() {}

func (x *DeleteCardReq) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCardReq.ProtoReflect.Descriptor instead.
func (*DeleteCardReq) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteCardReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteCardReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCardReply) Reset() {
	*x = DeleteCardReply{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCardReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCardReply) ProtoMessage() {}

func (x *DeleteCardReply) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCardReply.ProtoReflect.Descriptor instead.
func (*DeleteCardReply) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{27}
}

func (x *DeleteCardReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ListBeerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNum       int64                  `protobuf:"varint,1,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBeerReq) Reset() {
	*x = ListBeerReq{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBeerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBeerReq) ProtoMessage() {}

func (x *ListBeerReq) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBeerReq.ProtoReflect.Descriptor instead.
func (*ListBeerReq) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{28}
}

func (x *ListBeerReq) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *ListBeerReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListBeerReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ListBeerReply_Beer  `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBeerReply) Reset() {
	*x = ListBeerReply{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBeerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBeerReply) ProtoMessage() {}

func (x *ListBeerReply) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBeerReply.ProtoReflect.Descriptor instead.
func (*ListBeerReply) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{29}
}

func (x *ListBeerReply) GetResults() []*ListBeerReply_Beer {
	if x != nil {
		return x.Results
	}
	return nil
}

type GetBeerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBeerReq) Reset() {
	*x = GetBeerReq{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBeerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBeerReq) ProtoMessage() {}

func (x *GetBeerReq) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBeerReq.ProtoReflect.Descriptor instead.
func (*GetBeerReq) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{30}
}

func (x *GetBeerReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetBeerReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Count         int64                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Image         []*GetBeerReply_Image  `protobuf:"bytes,5,rep,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBeerReply) Reset() {
	*x = GetBeerReply{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBeerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBeerReply) ProtoMessage() {}

func (x *GetBeerReply) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBeerReply.ProtoReflect.Descriptor instead.
func (*GetBeerReply) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{31}
}

func (x *GetBeerReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetBeerReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetBeerReply) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetBeerReply) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetBeerReply) GetImage() []*GetBeerReply_Image {
	if x != nil {
		return x.Image
	}
	return nil
}

type ListCartItemReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNum       int64                  `protobuf:"varint,1,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCartItemReq) Reset() {
	*x = ListCartItemReq{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCartItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCartItemReq) ProtoMessage() {}

func (x *ListCartItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCartItemReq.ProtoReflect.Descriptor instead.
func (*ListCartItemReq) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{32}
}

func (x *ListCartItemReq) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *ListCartItemReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListCartItemReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCartItemReply) Reset() {
	*x = ListCartItemReply{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCartItemReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCartItemReply) ProtoMessage() {}

func (x *ListCartItemReply) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCartItemReply.ProtoReflect.Descriptor instead.
func (*ListCartItemReply) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{33}
}

type AddCartItemReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCartItemReq) Reset() {
	*x = AddCartItemReq{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCartItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCartItemReq) ProtoMessage() {}

func (x *AddCartItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCartItemReq.ProtoReflect.Descriptor instead.
func (*AddCartItemReq) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{34}
}

type AddCartItemReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCartItemReply) Reset() {
	*x = AddCartItemReply{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCartItemReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCartItemReply) ProtoMessage() {}

func (x *AddCartItemReply) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCartItemReply.ProtoReflect.Descriptor instead.
func (*AddCartItemReply) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{35}
}

type CreateOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderReq) Reset() {
	*x = CreateOrderReq{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReq) ProtoMessage() {}

func (x *CreateOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReq.ProtoReflect.Descriptor instead.
func (*CreateOrderReq) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{36}
}

type CreateOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderReply) Reset() {
	*x = CreateOrderReply{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReply) ProtoMessage() {}

func (x *CreateOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReply.ProtoReflect.Descriptor instead.
func (*CreateOrderReply) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{37}
}

type ListOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNum       int64                  `protobuf:"varint,1,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderReq) Reset() {
	*x = ListOrderReq{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderReq) ProtoMessage() {}

func (x *ListOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderReq.ProtoReflect.Descriptor instead.
func (*ListOrderReq) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{38}
}

func (x *ListOrderReq) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *ListOrderReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderReply) Reset() {
	*x = ListOrderReply{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderReply) ProtoMessage() {}

func (x *ListOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderReply.ProtoReflect.Descriptor instead.
func (*ListOrderReply) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{39}
}

type GetOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderReq) Reset() {
	*x = GetOrderReq{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderReq) ProtoMessage() {}

func (x *GetOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderReq.ProtoReflect.Descriptor instead.
func (*GetOrderReq) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{40}
}

type GetOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderReply) Reset() {
	*x = GetOrderReply{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderReply) ProtoMessage() {}

func (x *GetOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderReply.ProtoReflect.Descriptor instead.
func (*GetOrderReply) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{41}
}

type CreateBeerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Count         int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Image         []*CreateBeerReq_Image `protobuf:"bytes,4,rep,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBeerReq) Reset() {
	*x = CreateBeerReq{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBeerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBeerReq) ProtoMessage() {}

func (x *CreateBeerReq) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBeerReq.ProtoReflect.Descriptor instead.
func (*CreateBeerReq) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{42}
}

func (x *CreateBeerReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateBeerReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateBeerReq) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *CreateBeerReq) GetImage() []*CreateBeerReq_Image {
	if x != nil {
		return x.Image
	}
	return nil
}

type CreateBeerReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBeerReply) Reset() {
	*x = CreateBeerReply{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBeerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBeerReply) ProtoMessage() {}

func (x *CreateBeerReply) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBeerReply.ProtoReflect.Descriptor instead.
func (*CreateBeerReply) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{43}
}

type UpdateBeerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Count         int64                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Image         []*UpdateBeerReq_Image `protobuf:"bytes,5,rep,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBeerReq) Reset() {
	*x = UpdateBeerReq{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBeerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBeerReq) ProtoMessage() {}

func (x *UpdateBeerReq) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBeerReq.ProtoReflect.Descriptor instead.
func (*UpdateBeerReq) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{44}
}

func (x *UpdateBeerReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateBeerReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateBeerReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateBeerReq) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *UpdateBeerReq) GetImage() []*UpdateBeerReq_Image {
	if x != nil {
		return x.Image
	}
	return nil
}

type UpdateBeerReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBeerReply) Reset() {
	*x = UpdateBeerReply{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBeerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBeerReply) ProtoMessage() {}

func (x *UpdateBeerReply) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBeerReply.ProtoReflect.Descriptor instead.
func (*UpdateBeerReply) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{45}
}

type DeleteBeerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBeerReq) Reset() {
	*x = DeleteBeerReq{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[46]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBeerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBeerReq) ProtoMessage() {}

func (x *DeleteBeerReq) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[46]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBeerReq.ProtoReflect.Descriptor instead.
func (*DeleteBeerReq) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{46}
}

func (x *DeleteBeerReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteBeerReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBeerReply) Reset() {
	*x = DeleteBeerReply{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[47]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBeerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBeerReply) ProtoMessage() {}

func (x *DeleteBeerReply) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[47]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBeerReply.ProtoReflect.Descriptor instead.
func (*DeleteBeerReply) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{47}
}

type ListAddressReply_Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mobile        string                 `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Country       string                 `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	City          string                 `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	Address       string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	PostCode      string                 `protobuf:"bytes,7,opt,name=post_code,json=postCode,proto3" json:"post_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAddressReply_Address) Reset() {
	*x = ListAddressReply_Address{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[48]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAddressReply_Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAddressReply_Address) ProtoMessage() {}

func (x *ListAddressReply_Address) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[48]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAddressReply_Address.ProtoReflect.Descriptor instead.
func (*ListAddressReply_Address) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{15, 0}
}

func (x *ListAddressReply_Address) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListAddressReply_Address) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListAddressReply_Address) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *ListAddressReply_Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *ListAddressReply_Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ListAddressReply_Address) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ListAddressReply_Address) GetPostCode() string {
	if x != nil {
		return x.PostCode
	}
	return ""
}

type ListCardReply_Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CardNo        string                 `protobuf:"bytes,2,opt,name=card_no,json=cardNo,proto3" json:"card_no,omitempty"`
	Ccv           string                 `protobuf:"bytes,3,opt,name=ccv,proto3" json:"ccv,omitempty"`
	Expires       string                 `protobuf:"bytes,4,opt,name=expires,proto3" json:"expires,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCardReply_Card) Reset() {
	*x = ListCardReply_Card{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[49]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCardReply_Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCardReply_Card) ProtoMessage() {}

func (x *ListCardReply_Card) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[49]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCardReply_Card.ProtoReflect.Descriptor instead.
func (*ListCardReply_Card) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{21, 0}
}

func (x *ListCardReply_Card) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListCardReply_Card) GetCardNo() string {
	if x != nil {
		return x.CardNo
	}
	return ""
}

func (x *ListCardReply_Card) GetCcv() string {
	if x != nil {
		return x.Ccv
	}
	return ""
}

func (x *ListCardReply_Card) GetExpires() string {
	if x != nil {
		return x.Expires
	}
	return ""
}

type ListBeerReply_Beer struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Id            int64                       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                      `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Count         int64                       `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Image         []*ListBeerReply_Beer_Image `protobuf:"bytes,5,rep,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBeerReply_Beer) Reset() {
	*x = ListBeerReply_Beer{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[50]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBeerReply_Beer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBeerReply_Beer) ProtoMessage() {}

func (x *ListBeerReply_Beer) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[50]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBeerReply_Beer.ProtoReflect.Descriptor instead.
func (*ListBeerReply_Beer) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{29, 0}
}

func (x *ListBeerReply_Beer) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListBeerReply_Beer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListBeerReply_Beer) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ListBeerReply_Beer) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ListBeerReply_Beer) GetImage() []*ListBeerReply_Beer_Image {
	if x != nil {
		return x.Image
	}
	return nil
}

type ListBeerReply_Beer_Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBeerReply_Beer_Image) Reset() {
	*x = ListBeerReply_Beer_Image{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[51]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBeerReply_Beer_Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBeerReply_Beer_Image) ProtoMessage() {}

func (x *ListBeerReply_Beer_Image) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[51]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBeerReply_Beer_Image.ProtoReflect.Descriptor instead.
func (*ListBeerReply_Beer_Image) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{29, 0, 0}
}

func (x *ListBeerReply_Beer_Image) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetBeerReply_Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBeerReply_Image) Reset() {
	*x = GetBeerReply_Image{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[52]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBeerReply_Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBeerReply_Image) ProtoMessage() {}

func (x *GetBeerReply_Image) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[52]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBeerReply_Image.ProtoReflect.Descriptor instead.
func (*GetBeerReply_Image) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{31, 0}
}

func (x *GetBeerReply_Image) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CreateBeerReq_Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBeerReq_Image) Reset() {
	*x = CreateBeerReq_Image{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[53]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBeerReq_Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBeerReq_Image) ProtoMessage() {}

func (x *CreateBeerReq_Image) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[53]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBeerReq_Image.ProtoReflect.Descriptor instead.
func (*CreateBeerReq_Image) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{42, 0}
}

func (x *CreateBeerReq_Image) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type UpdateBeerReq_Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBeerReq_Image) Reset() {
	*x = UpdateBeerReq_Image{}
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[54]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBeerReq_Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBeerReq_Image) ProtoMessage() {}

func (x *UpdateBeerReq_Image) ProtoReflect() protoreflect.Message {
	mi := &file_shop_admin_v1_shop_admin_proto_msgTypes[54]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBeerReq_Image.ProtoReflect.Descriptor instead.
func (*UpdateBeerReq_Image) Descriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_proto_rawDescGZIP(), []int{44, 0}
}

func (x *UpdateBeerReq_Image) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_shop_admin_v1_shop_admin_proto protoreflect.FileDescriptor

const file_shop_admin_v1_shop_admin_proto_rawDesc = "" +
	"\n" +
	"\x1eshop/admin/v1/shop_admin.proto\x12\rshop.admin.v1\x1a\x1cgoogle/api/annotations.proto\"E\n" +
	"\vRegisterReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x1f\n" +
	"\rRegisterReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"B\n" +
	"\bLoginReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\"\n" +
	"\n" +
	"LoginReply\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\v\n" +
	"\tLogoutReq\"\r\n" +
	"\vLogoutReply\"\x1c\n" +
	"\n" +
	"GetUserReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\":\n" +
	"\fGetUserReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"\r\n" +
	"\vListUserReq\"\x0f\n" +
	"\rListUserReply\"G\n" +
	"\rCreateUserReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"=\n" +
	"\x0fCreateUserReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"K\n" +
	"\x11VerifyPasswordReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"5\n" +
	"\x13VerifyPasswordReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\"\"\n" +
	"\x0eListAddressReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\"\x82\x02\n" +
	"\x10ListAddressReply\x12A\n" +
	"\aresults\x18\x01 \x03(\v2'.shop.admin.v1.ListAddressReply.AddressR\aresults\x1a\xaa\x01\n" +
	"\aAddress\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06mobile\x18\x03 \x01(\tR\x06mobile\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\x12\x18\n" +
	"\aaddress\x18\x06 \x01(\tR\aaddress\x12\x1b\n" +
	"\tpost_code\x18\a \x01(\tR\bpostCode\"\xb5\x01\n" +
	"\x10CreateAddressReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06mobile\x18\x03 \x01(\tR\x06mobile\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\x12\x18\n" +
	"\aaddress\x18\x06 \x01(\tR\aaddress\x12\x1b\n" +
	"\tpost_code\x18\a \x01(\tR\bpostCode\"\xb5\x01\n" +
	"\x12CreateAddressReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06mobile\x18\x03 \x01(\tR\x06mobile\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\x12\x18\n" +
	"\aaddress\x18\x06 \x01(\tR\aaddress\x12\x1b\n" +
	"\tpost_code\x18\a \x01(\tR\bpostCode\"\x1f\n" +
	"\rGetAddressReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xb2\x01\n" +
	"\x0fGetAddressReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06mobile\x18\x03 \x01(\tR\x06mobile\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\x12\x18\n" +
	"\aaddress\x18\x06 \x01(\tR\aaddress\x12\x1b\n" +
	"\tpost_code\x18\a \x01(\tR\bpostCode\"\x1f\n" +
	"\vListCardReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\"\xa9\x01\n" +
	"\rListCardReply\x12;\n" +
	"\aresults\x18\x01 \x03(\v2!.shop.admin.v1.ListCardReply.CardR\aresults\x1a[\n" +
	"\x04Card\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\acard_no\x18\x02 \x01(\tR\x06cardNo\x12\x10\n" +
	"\x03ccv\x18\x03 \x01(\tR\x03ccv\x12\x18\n" +
	"\aexpires\x18\x04 \x01(\tR\aexpires\"f\n" +
	"\rCreateCardReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x17\n" +
	"\acard_no\x18\x02 \x01(\tR\x06cardNo\x12\x10\n" +
	"\x03ccv\x18\x03 \x01(\tR\x03ccv\x12\x18\n" +
	"\aexpires\x18\x04 \x01(\tR\aexpires\"!\n" +
	"\x0fCreateCardReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x1c\n" +
	"\n" +
	"GetCardReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"c\n" +
	"\fGetCardReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\acard_no\x18\x02 \x01(\tR\x06cardNo\x12\x10\n" +
	"\x03ccv\x18\x03 \x01(\tR\x03ccv\x12\x18\n" +
	"\aexpires\x18\x04 \x01(\tR\aexpires\"\x1f\n" +
	"\rDeleteCardReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"!\n" +
	"\x0fDeleteCardReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"E\n" +
	"\vListBeerReq\x12\x19\n" +
	"\bpage_num\x18\x01 \x01(\x03R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\"\x8b\x02\n" +
	"\rListBeerReply\x12;\n" +
	"\aresults\x18\x01 \x03(\v2!.shop.admin.v1.ListBeerReply.BeerR\aresults\x1a\xbc\x01\n" +
	"\x04Beer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x03R\x05count\x12=\n" +
	"\x05image\x18\x05 \x03(\v2'.shop.admin.v1.ListBeerReply.Beer.ImageR\x05image\x1a\x19\n" +
	"\x05Image\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x1c\n" +
	"\n" +
	"GetBeerReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xbe\x01\n" +
	"\fGetBeerReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x03R\x05count\x127\n" +
	"\x05image\x18\x05 \x03(\v2!.shop.admin.v1.GetBeerReply.ImageR\x05image\x1a\x19\n" +
	"\x05Image\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"I\n" +
	"\x0fListCartItemReq\x12\x19\n" +
	"\bpage_num\x18\x01 \x01(\x03R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\"\x13\n" +
	"\x11ListCartItemReply\"\x10\n" +
	"\x0eAddCartItemReq\"\x12\n" +
	"\x10AddCartItemReply\"\x10\n" +
	"\x0eCreateOrderReq\"\x12\n" +
	"\x10CreateOrderReply\"F\n" +
	"\fListOrderReq\x12\x19\n" +
	"\bpage_num\x18\x01 \x01(\x03R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\"\x10\n" +
	"\x0eListOrderReply\"\r\n" +
	"\vGetOrderReq\"\x0f\n" +
	"\rGetOrderReply\"\xb0\x01\n" +
	"\rCreateBeerReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\x128\n" +
	"\x05image\x18\x04 \x03(\v2\".shop.admin.v1.CreateBeerReq.ImageR\x05image\x1a\x19\n" +
	"\x05Image\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x11\n" +
	"\x0fCreateBeerReply\"\xc0\x01\n" +
	"\rUpdateBeerReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x03R\x05count\x128\n" +
	"\x05image\x18\x05 \x03(\v2\".shop.admin.v1.UpdateBeerReq.ImageR\x05image\x1a\x19\n" +
	"\x05Image\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x11\n" +
	"\x0fUpdateBeerReply\"\x1f\n" +
	"\rDeleteBeerReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x11\n" +
	"\x0fDeleteBeerReply2\x82\b\n" +
	"\tShopAdmin\x12W\n" +
	"\x05Login\x12\x17.shop.admin.v1.LoginReq\x1a\x19.shop.admin.v1.LoginReply\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/admin/v1/login\x12[\n" +
	"\x06Logout\x12\x18.shop.admin.v1.LogoutReq\x1a\x1a.shop.admin.v1.LogoutReply\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/admin/v1/logout\x12e\n" +
	"\bListBeer\x12\x1a.shop.admin.v1.ListBeerReq\x1a\x1c.shop.admin.v1.ListBeerReply\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/admin/v1/catalog/beers\x12n\n" +
	"\n" +
	"CreateBeer\x12\x1c.shop.admin.v1.CreateBeerReq\x1a\x1e.shop.admin.v1.CreateBeerReply\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/admin/v1/catalog/beers\x12s\n" +
	"\n" +
	"UpdateBeer\x12\x1c.shop.admin.v1.UpdateBeerReq\x1a\x1e.shop.admin.v1.UpdateBeerReply\"'\x82\xd3\xe4\x93\x02!:\x01*\x1a\x1c/admin/v1/catalog/beers/{id}\x12p\n" +
	"\n" +
	"DeleteBeer\x12\x1c.shop.admin.v1.DeleteBeerReq\x1a\x1e.shop.admin.v1.DeleteBeerReply\"$\x82\xd3\xe4\x93\x02\x1e*\x1c/admin/v1/catalog/beers/{id}\x12a\n" +
	"\tListOrder\x12\x1b.shop.admin.v1.ListOrderReq\x1a\x1d.shop.admin.v1.ListOrderReply\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/admin/v1/orders\x12^\n" +
	"\bGetOrder\x12\x1a.shop.admin.v1.GetOrderReq\x1a\x1c.shop.admin.v1.GetOrderReply\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/admin/v1/orders\x12]\n" +
	"\bListUser\x12\x1a.shop.admin.v1.ListUserReq\x1a\x1c.shop.admin.v1.ListUserReply\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/admin/v1/users\x12_\n" +
	"\aGetUser\x12\x19.shop.admin.v1.GetUserReq\x1a\x1b.shop.admin.v1.GetUserReply\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/admin/v1/users/{id}B\xb6\x01\n" +
	"\x11com.shop.admin.v1B\x0eShopAdminProtoP\x01Z;tlgitea.com/pingtai/gopkg/api/_gen/go/shop/admin/v1;adminv1\xa2\x02\x03SAX\xaa\x02\rShop.Admin.V1\xca\x02\rShop\\Admin\\V1\xe2\x02\x19Shop\\Admin\\V1\\GPBMetadata\xea\x02\x0fShop::Admin::V1b\x06proto3"

var (
	file_shop_admin_v1_shop_admin_proto_rawDescOnce sync.Once
	file_shop_admin_v1_shop_admin_proto_rawDescData []byte
)

func file_shop_admin_v1_shop_admin_proto_rawDescGZIP() []byte {
	file_shop_admin_v1_shop_admin_proto_rawDescOnce.Do(func() {
		file_shop_admin_v1_shop_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shop_admin_v1_shop_admin_proto_rawDesc), len(file_shop_admin_v1_shop_admin_proto_rawDesc)))
	})
	return file_shop_admin_v1_shop_admin_proto_rawDescData
}

var file_shop_admin_v1_shop_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 55)
var file_shop_admin_v1_shop_admin_proto_goTypes = []any{
	(*RegisterReq)(nil),              // 0: shop.admin.v1.RegisterReq
	(*RegisterReply)(nil),            // 1: shop.admin.v1.RegisterReply
	(*LoginReq)(nil),                 // 2: shop.admin.v1.LoginReq
	(*LoginReply)(nil),               // 3: shop.admin.v1.LoginReply
	(*LogoutReq)(nil),                // 4: shop.admin.v1.LogoutReq
	(*LogoutReply)(nil),              // 5: shop.admin.v1.LogoutReply
	(*GetUserReq)(nil),               // 6: shop.admin.v1.GetUserReq
	(*GetUserReply)(nil),             // 7: shop.admin.v1.GetUserReply
	(*ListUserReq)(nil),              // 8: shop.admin.v1.ListUserReq
	(*ListUserReply)(nil),            // 9: shop.admin.v1.ListUserReply
	(*CreateUserReq)(nil),            // 10: shop.admin.v1.CreateUserReq
	(*CreateUserReply)(nil),          // 11: shop.admin.v1.CreateUserReply
	(*VerifyPasswordReq)(nil),        // 12: shop.admin.v1.VerifyPasswordReq
	(*VerifyPasswordReply)(nil),      // 13: shop.admin.v1.VerifyPasswordReply
	(*ListAddressReq)(nil),           // 14: shop.admin.v1.ListAddressReq
	(*ListAddressReply)(nil),         // 15: shop.admin.v1.ListAddressReply
	(*CreateAddressReq)(nil),         // 16: shop.admin.v1.CreateAddressReq
	(*CreateAddressReply)(nil),       // 17: shop.admin.v1.CreateAddressReply
	(*GetAddressReq)(nil),            // 18: shop.admin.v1.GetAddressReq
	(*GetAddressReply)(nil),          // 19: shop.admin.v1.GetAddressReply
	(*ListCardReq)(nil),              // 20: shop.admin.v1.ListCardReq
	(*ListCardReply)(nil),            // 21: shop.admin.v1.ListCardReply
	(*CreateCardReq)(nil),            // 22: shop.admin.v1.CreateCardReq
	(*CreateCardReply)(nil),          // 23: shop.admin.v1.CreateCardReply
	(*GetCardReq)(nil),               // 24: shop.admin.v1.GetCardReq
	(*GetCardReply)(nil),             // 25: shop.admin.v1.GetCardReply
	(*DeleteCardReq)(nil),            // 26: shop.admin.v1.DeleteCardReq
	(*DeleteCardReply)(nil),          // 27: shop.admin.v1.DeleteCardReply
	(*ListBeerReq)(nil),              // 28: shop.admin.v1.ListBeerReq
	(*ListBeerReply)(nil),            // 29: shop.admin.v1.ListBeerReply
	(*GetBeerReq)(nil),               // 30: shop.admin.v1.GetBeerReq
	(*GetBeerReply)(nil),             // 31: shop.admin.v1.GetBeerReply
	(*ListCartItemReq)(nil),          // 32: shop.admin.v1.ListCartItemReq
	(*ListCartItemReply)(nil),        // 33: shop.admin.v1.ListCartItemReply
	(*AddCartItemReq)(nil),           // 34: shop.admin.v1.AddCartItemReq
	(*AddCartItemReply)(nil),         // 35: shop.admin.v1.AddCartItemReply
	(*CreateOrderReq)(nil),           // 36: shop.admin.v1.CreateOrderReq
	(*CreateOrderReply)(nil),         // 37: shop.admin.v1.CreateOrderReply
	(*ListOrderReq)(nil),             // 38: shop.admin.v1.ListOrderReq
	(*ListOrderReply)(nil),           // 39: shop.admin.v1.ListOrderReply
	(*GetOrderReq)(nil),              // 40: shop.admin.v1.GetOrderReq
	(*GetOrderReply)(nil),            // 41: shop.admin.v1.GetOrderReply
	(*CreateBeerReq)(nil),            // 42: shop.admin.v1.CreateBeerReq
	(*CreateBeerReply)(nil),          // 43: shop.admin.v1.CreateBeerReply
	(*UpdateBeerReq)(nil),            // 44: shop.admin.v1.UpdateBeerReq
	(*UpdateBeerReply)(nil),          // 45: shop.admin.v1.UpdateBeerReply
	(*DeleteBeerReq)(nil),            // 46: shop.admin.v1.DeleteBeerReq
	(*DeleteBeerReply)(nil),          // 47: shop.admin.v1.DeleteBeerReply
	(*ListAddressReply_Address)(nil), // 48: shop.admin.v1.ListAddressReply.Address
	(*ListCardReply_Card)(nil),       // 49: shop.admin.v1.ListCardReply.Card
	(*ListBeerReply_Beer)(nil),       // 50: shop.admin.v1.ListBeerReply.Beer
	(*ListBeerReply_Beer_Image)(nil), // 51: shop.admin.v1.ListBeerReply.Beer.Image
	(*GetBeerReply_Image)(nil),       // 52: shop.admin.v1.GetBeerReply.Image
	(*CreateBeerReq_Image)(nil),      // 53: shop.admin.v1.CreateBeerReq.Image
	(*UpdateBeerReq_Image)(nil),      // 54: shop.admin.v1.UpdateBeerReq.Image
}
var file_shop_admin_v1_shop_admin_proto_depIdxs = []int32{
	48, // 0: shop.admin.v1.ListAddressReply.results:type_name -> shop.admin.v1.ListAddressReply.Address
	49, // 1: shop.admin.v1.ListCardReply.results:type_name -> shop.admin.v1.ListCardReply.Card
	50, // 2: shop.admin.v1.ListBeerReply.results:type_name -> shop.admin.v1.ListBeerReply.Beer
	52, // 3: shop.admin.v1.GetBeerReply.image:type_name -> shop.admin.v1.GetBeerReply.Image
	53, // 4: shop.admin.v1.CreateBeerReq.image:type_name -> shop.admin.v1.CreateBeerReq.Image
	54, // 5: shop.admin.v1.UpdateBeerReq.image:type_name -> shop.admin.v1.UpdateBeerReq.Image
	51, // 6: shop.admin.v1.ListBeerReply.Beer.image:type_name -> shop.admin.v1.ListBeerReply.Beer.Image
	2,  // 7: shop.admin.v1.ShopAdmin.Login:input_type -> shop.admin.v1.LoginReq
	4,  // 8: shop.admin.v1.ShopAdmin.Logout:input_type -> shop.admin.v1.LogoutReq
	28, // 9: shop.admin.v1.ShopAdmin.ListBeer:input_type -> shop.admin.v1.ListBeerReq
	42, // 10: shop.admin.v1.ShopAdmin.CreateBeer:input_type -> shop.admin.v1.CreateBeerReq
	44, // 11: shop.admin.v1.ShopAdmin.UpdateBeer:input_type -> shop.admin.v1.UpdateBeerReq
	46, // 12: shop.admin.v1.ShopAdmin.DeleteBeer:input_type -> shop.admin.v1.DeleteBeerReq
	38, // 13: shop.admin.v1.ShopAdmin.ListOrder:input_type -> shop.admin.v1.ListOrderReq
	40, // 14: shop.admin.v1.ShopAdmin.GetOrder:input_type -> shop.admin.v1.GetOrderReq
	8,  // 15: shop.admin.v1.ShopAdmin.ListUser:input_type -> shop.admin.v1.ListUserReq
	6,  // 16: shop.admin.v1.ShopAdmin.GetUser:input_type -> shop.admin.v1.GetUserReq
	3,  // 17: shop.admin.v1.ShopAdmin.Login:output_type -> shop.admin.v1.LoginReply
	5,  // 18: shop.admin.v1.ShopAdmin.Logout:output_type -> shop.admin.v1.LogoutReply
	29, // 19: shop.admin.v1.ShopAdmin.ListBeer:output_type -> shop.admin.v1.ListBeerReply
	43, // 20: shop.admin.v1.ShopAdmin.CreateBeer:output_type -> shop.admin.v1.CreateBeerReply
	45, // 21: shop.admin.v1.ShopAdmin.UpdateBeer:output_type -> shop.admin.v1.UpdateBeerReply
	47, // 22: shop.admin.v1.ShopAdmin.DeleteBeer:output_type -> shop.admin.v1.DeleteBeerReply
	39, // 23: shop.admin.v1.ShopAdmin.ListOrder:output_type -> shop.admin.v1.ListOrderReply
	41, // 24: shop.admin.v1.ShopAdmin.GetOrder:output_type -> shop.admin.v1.GetOrderReply
	9,  // 25: shop.admin.v1.ShopAdmin.ListUser:output_type -> shop.admin.v1.ListUserReply
	7,  // 26: shop.admin.v1.ShopAdmin.GetUser:output_type -> shop.admin.v1.GetUserReply
	17, // [17:27] is the sub-list for method output_type
	7,  // [7:17] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_shop_admin_v1_shop_admin_proto_init() }
func file_shop_admin_v1_shop_admin_proto_init() {
	if File_shop_admin_v1_shop_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shop_admin_v1_shop_admin_proto_rawDesc), len(file_shop_admin_v1_shop_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   55,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shop_admin_v1_shop_admin_proto_goTypes,
		DependencyIndexes: file_shop_admin_v1_shop_admin_proto_depIdxs,
		MessageInfos:      file_shop_admin_v1_shop_admin_proto_msgTypes,
	}.Build()
	File_shop_admin_v1_shop_admin_proto = out.File
	file_shop_admin_v1_shop_admin_proto_goTypes = nil
	file_shop_admin_v1_shop_admin_proto_depIdxs = nil
}
