// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: shop/admin/v1/shop_admin_error.proto

package adminv1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShopAdminErrorReason int32

const (
	ShopAdminErrorReason_UNKNOWN_ERROR ShopAdminErrorReason = 0
)

// Enum value maps for ShopAdminErrorReason.
var (
	ShopAdminErrorReason_name = map[int32]string{
		0: "UNKNOWN_ERROR",
	}
	ShopAdminErrorReason_value = map[string]int32{
		"UNKNOWN_ERROR": 0,
	}
)

func (x ShopAdminErrorReason) Enum() *ShopAdminErrorReason {
	p := new(ShopAdminErrorReason)
	*p = x
	return p
}

func (x ShopAdminErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShopAdminErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_shop_admin_v1_shop_admin_error_proto_enumTypes[0].Descriptor()
}

func (ShopAdminErrorReason) Type() protoreflect.EnumType {
	return &file_shop_admin_v1_shop_admin_error_proto_enumTypes[0]
}

func (x ShopAdminErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShopAdminErrorReason.Descriptor instead.
func (ShopAdminErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_shop_admin_v1_shop_admin_error_proto_rawDescGZIP(), []int{0}
}

var File_shop_admin_v1_shop_admin_error_proto protoreflect.FileDescriptor

const file_shop_admin_v1_shop_admin_error_proto_rawDesc = "" +
	"\n" +
	"$shop/admin/v1/shop_admin_error.proto\x12\rshop.admin.v1\x1a\x13errors/errors.proto*/\n" +
	"\x14ShopAdminErrorReason\x12\x11\n" +
	"\rUNKNOWN_ERROR\x10\x00\x1a\x04\xa0E\xf4\x03B\xbb\x01\n" +
	"\x11com.shop.admin.v1B\x13ShopAdminErrorProtoP\x01Z;tlgitea.com/pingtai/gopkg/api/_gen/go/shop/admin/v1;adminv1\xa2\x02\x03SAX\xaa\x02\rShop.Admin.V1\xca\x02\rShop\\Admin\\V1\xe2\x02\x19Shop\\Admin\\V1\\GPBMetadata\xea\x02\x0fShop::Admin::V1b\x06proto3"

var (
	file_shop_admin_v1_shop_admin_error_proto_rawDescOnce sync.Once
	file_shop_admin_v1_shop_admin_error_proto_rawDescData []byte
)

func file_shop_admin_v1_shop_admin_error_proto_rawDescGZIP() []byte {
	file_shop_admin_v1_shop_admin_error_proto_rawDescOnce.Do(func() {
		file_shop_admin_v1_shop_admin_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shop_admin_v1_shop_admin_error_proto_rawDesc), len(file_shop_admin_v1_shop_admin_error_proto_rawDesc)))
	})
	return file_shop_admin_v1_shop_admin_error_proto_rawDescData
}

var file_shop_admin_v1_shop_admin_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shop_admin_v1_shop_admin_error_proto_goTypes = []any{
	(ShopAdminErrorReason)(0), // 0: shop.admin.v1.ShopAdminErrorReason
}
var file_shop_admin_v1_shop_admin_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shop_admin_v1_shop_admin_error_proto_init() }
func file_shop_admin_v1_shop_admin_error_proto_init() {
	if File_shop_admin_v1_shop_admin_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shop_admin_v1_shop_admin_error_proto_rawDesc), len(file_shop_admin_v1_shop_admin_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shop_admin_v1_shop_admin_error_proto_goTypes,
		DependencyIndexes: file_shop_admin_v1_shop_admin_error_proto_depIdxs,
		EnumInfos:         file_shop_admin_v1_shop_admin_error_proto_enumTypes,
	}.Build()
	File_shop_admin_v1_shop_admin_error_proto = out.File
	file_shop_admin_v1_shop_admin_error_proto_goTypes = nil
	file_shop_admin_v1_shop_admin_error_proto_depIdxs = nil
}
