// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: shop/interface/v1/shop_interface_error.proto

package interfacev1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShopInterfaceErrorReason int32

const (
	ShopInterfaceErrorReason_UNKNOWN_ERROR     ShopInterfaceErrorReason = 0
	ShopInterfaceErrorReason_LOGIN_FAILED      ShopInterfaceErrorReason = 1
	ShopInterfaceErrorReason_USERNAME_CONFLICT ShopInterfaceErrorReason = 2
	ShopInterfaceErrorReason_REGISTER_FAILED   ShopInterfaceErrorReason = 3
)

// Enum value maps for ShopInterfaceErrorReason.
var (
	ShopInterfaceErrorReason_name = map[int32]string{
		0: "UNKNOWN_ERROR",
		1: "LOGIN_FAILED",
		2: "USERNAME_CONFLICT",
		3: "REGISTER_FAILED",
	}
	ShopInterfaceErrorReason_value = map[string]int32{
		"UNKNOWN_ERROR":     0,
		"LOGIN_FAILED":      1,
		"USERNAME_CONFLICT": 2,
		"REGISTER_FAILED":   3,
	}
)

func (x ShopInterfaceErrorReason) Enum() *ShopInterfaceErrorReason {
	p := new(ShopInterfaceErrorReason)
	*p = x
	return p
}

func (x ShopInterfaceErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShopInterfaceErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_shop_interface_v1_shop_interface_error_proto_enumTypes[0].Descriptor()
}

func (ShopInterfaceErrorReason) Type() protoreflect.EnumType {
	return &file_shop_interface_v1_shop_interface_error_proto_enumTypes[0]
}

func (x ShopInterfaceErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShopInterfaceErrorReason.Descriptor instead.
func (ShopInterfaceErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_shop_interface_v1_shop_interface_error_proto_rawDescGZIP(), []int{0}
}

var File_shop_interface_v1_shop_interface_error_proto protoreflect.FileDescriptor

const file_shop_interface_v1_shop_interface_error_proto_rawDesc = "" +
	"\n" +
	",shop/interface/v1/shop_interface_error.proto\x12\x11shop.interface.v1\x1a\x13errors/errors.proto*\x83\x01\n" +
	"\x18ShopInterfaceErrorReason\x12\x11\n" +
	"\rUNKNOWN_ERROR\x10\x00\x12\x16\n" +
	"\fLOGIN_FAILED\x10\x01\x1a\x04\xa8E\x91\x03\x12\x1b\n" +
	"\x11USERNAME_CONFLICT\x10\x02\x1a\x04\xa8E\x99\x03\x12\x19\n" +
	"\x0fREGISTER_FAILED\x10\x03\x1a\x04\xa8E\x9d\x04\x1a\x04\xa0E\xf4\x03B\xdd\x01\n" +
	"\x15com.shop.interface.v1B\x17ShopInterfaceErrorProtoP\x01ZCtlgitea.com/pingtai/gopkg/api/_gen/go/shop/interface/v1;interfacev1\xa2\x02\x03SIX\xaa\x02\x11Shop.Interface.V1\xca\x02\x12Shop\\Interface_\\V1\xe2\x02\x1eShop\\Interface_\\V1\\GPBMetadata\xea\x02\x13Shop::Interface::V1b\x06proto3"

var (
	file_shop_interface_v1_shop_interface_error_proto_rawDescOnce sync.Once
	file_shop_interface_v1_shop_interface_error_proto_rawDescData []byte
)

func file_shop_interface_v1_shop_interface_error_proto_rawDescGZIP() []byte {
	file_shop_interface_v1_shop_interface_error_proto_rawDescOnce.Do(func() {
		file_shop_interface_v1_shop_interface_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shop_interface_v1_shop_interface_error_proto_rawDesc), len(file_shop_interface_v1_shop_interface_error_proto_rawDesc)))
	})
	return file_shop_interface_v1_shop_interface_error_proto_rawDescData
}

var file_shop_interface_v1_shop_interface_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shop_interface_v1_shop_interface_error_proto_goTypes = []any{
	(ShopInterfaceErrorReason)(0), // 0: shop.interface.v1.ShopInterfaceErrorReason
}
var file_shop_interface_v1_shop_interface_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shop_interface_v1_shop_interface_error_proto_init() }
func file_shop_interface_v1_shop_interface_error_proto_init() {
	if File_shop_interface_v1_shop_interface_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shop_interface_v1_shop_interface_error_proto_rawDesc), len(file_shop_interface_v1_shop_interface_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shop_interface_v1_shop_interface_error_proto_goTypes,
		DependencyIndexes: file_shop_interface_v1_shop_interface_error_proto_depIdxs,
		EnumInfos:         file_shop_interface_v1_shop_interface_error_proto_enumTypes,
	}.Build()
	File_shop_interface_v1_shop_interface_error_proto = out.File
	file_shop_interface_v1_shop_interface_error_proto_goTypes = nil
	file_shop_interface_v1_shop_interface_error_proto_depIdxs = nil
}
