// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: order/service/v1/order.proto

package servicev1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	PageNum       int64                  `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderReq) Reset() {
	*x = ListOrderReq{}
	mi := &file_order_service_v1_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderReq) ProtoMessage() {}

func (x *ListOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_v1_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderReq.ProtoReflect.Descriptor instead.
func (*ListOrderReq) Descriptor() ([]byte, []int) {
	return file_order_service_v1_order_proto_rawDescGZIP(), []int{0}
}

func (x *ListOrderReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ListOrderReq) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *ListOrderReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListOrderReply struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Orders        []*ListOrderReply_Order `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderReply) Reset() {
	*x = ListOrderReply{}
	mi := &file_order_service_v1_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderReply) ProtoMessage() {}

func (x *ListOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_v1_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderReply.ProtoReflect.Descriptor instead.
func (*ListOrderReply) Descriptor() ([]byte, []int) {
	return file_order_service_v1_order_proto_rawDescGZIP(), []int{1}
}

func (x *ListOrderReply) GetOrders() []*ListOrderReply_Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type CreateOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderReq) Reset() {
	*x = CreateOrderReq{}
	mi := &file_order_service_v1_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReq) ProtoMessage() {}

func (x *CreateOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_v1_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReq.ProtoReflect.Descriptor instead.
func (*CreateOrderReq) Descriptor() ([]byte, []int) {
	return file_order_service_v1_order_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreateOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderReply) Reset() {
	*x = CreateOrderReply{}
	mi := &file_order_service_v1_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReply) ProtoMessage() {}

func (x *CreateOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_v1_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReply.ProtoReflect.Descriptor instead.
func (*CreateOrderReply) Descriptor() ([]byte, []int) {
	return file_order_service_v1_order_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOrderReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateOrderReply) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderReq) Reset() {
	*x = GetOrderReq{}
	mi := &file_order_service_v1_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderReq) ProtoMessage() {}

func (x *GetOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_v1_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderReq.ProtoReflect.Descriptor instead.
func (*GetOrderReq) Descriptor() ([]byte, []int) {
	return file_order_service_v1_order_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrderReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderReply) Reset() {
	*x = GetOrderReply{}
	mi := &file_order_service_v1_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderReply) ProtoMessage() {}

func (x *GetOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_v1_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderReply.ProtoReflect.Descriptor instead.
func (*GetOrderReply) Descriptor() ([]byte, []int) {
	return file_order_service_v1_order_proto_rawDescGZIP(), []int{5}
}

func (x *GetOrderReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetOrderReply) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UpdateOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderReq) Reset() {
	*x = UpdateOrderReq{}
	mi := &file_order_service_v1_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderReq) ProtoMessage() {}

func (x *UpdateOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_v1_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderReq.ProtoReflect.Descriptor instead.
func (*UpdateOrderReq) Descriptor() ([]byte, []int) {
	return file_order_service_v1_order_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateOrderReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateOrderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UpdateOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderReply) Reset() {
	*x = UpdateOrderReply{}
	mi := &file_order_service_v1_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderReply) ProtoMessage() {}

func (x *UpdateOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_v1_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderReply.ProtoReflect.Descriptor instead.
func (*UpdateOrderReply) Descriptor() ([]byte, []int) {
	return file_order_service_v1_order_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateOrderReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateOrderReply) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListOrderReply_Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderReply_Order) Reset() {
	*x = ListOrderReply_Order{}
	mi := &file_order_service_v1_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderReply_Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderReply_Order) ProtoMessage() {}

func (x *ListOrderReply_Order) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_v1_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderReply_Order.ProtoReflect.Descriptor instead.
func (*ListOrderReply_Order) Descriptor() ([]byte, []int) {
	return file_order_service_v1_order_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ListOrderReply_Order) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListOrderReply_Order) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_order_service_v1_order_proto protoreflect.FileDescriptor

const file_order_service_v1_order_proto_rawDesc = "" +
	"\n" +
	"\x1corder/service/v1/order.proto\x12\x10order.service.v1\x1a\x1cgoogle/api/annotations.proto\"X\n" +
	"\fListOrderReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x19\n" +
	"\bpage_num\x18\x02 \x01(\x03R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x03R\bpageSize\"\x82\x01\n" +
	"\x0eListOrderReply\x12>\n" +
	"\x06orders\x18\x01 \x03(\v2&.order.service.v1.ListOrderReply.OrderR\x06orders\x1a0\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\")\n" +
	"\x0eCreateOrderReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\";\n" +
	"\x10CreateOrderReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\x1d\n" +
	"\vGetOrderReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"8\n" +
	"\rGetOrderReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"9\n" +
	"\x0eUpdateOrderReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\";\n" +
	"\x10UpdateOrderReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId2\xd4\x02\n" +
	"\x05Order\x12O\n" +
	"\tListOrder\x12\x1e.order.service.v1.ListOrderReq\x1a .order.service.v1.ListOrderReply\"\x00\x12U\n" +
	"\vCreateOrder\x12 .order.service.v1.CreateOrderReq\x1a\".order.service.v1.CreateOrderReply\"\x00\x12L\n" +
	"\bGetOrder\x12\x1d.order.service.v1.GetOrderReq\x1a\x1f.order.service.v1.GetOrderReply\"\x00\x12U\n" +
	"\vUpdateOrder\x12 .order.service.v1.UpdateOrderReq\x1a\".order.service.v1.UpdateOrderReply\"\x00B\xc6\x01\n" +
	"\x14com.order.service.v1B\n" +
	"OrderProtoP\x01Z@tlgitea.com/pingtai/gopkg/api/_gen/go/order/service/v1;servicev1\xa2\x02\x03OSX\xaa\x02\x10Order.Service.V1\xca\x02\x10Order\\Service\\V1\xe2\x02\x1cOrder\\Service\\V1\\GPBMetadata\xea\x02\x12Order::Service::V1b\x06proto3"

var (
	file_order_service_v1_order_proto_rawDescOnce sync.Once
	file_order_service_v1_order_proto_rawDescData []byte
)

func file_order_service_v1_order_proto_rawDescGZIP() []byte {
	file_order_service_v1_order_proto_rawDescOnce.Do(func() {
		file_order_service_v1_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_service_v1_order_proto_rawDesc), len(file_order_service_v1_order_proto_rawDesc)))
	})
	return file_order_service_v1_order_proto_rawDescData
}

var file_order_service_v1_order_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_order_service_v1_order_proto_goTypes = []any{
	(*ListOrderReq)(nil),         // 0: order.service.v1.ListOrderReq
	(*ListOrderReply)(nil),       // 1: order.service.v1.ListOrderReply
	(*CreateOrderReq)(nil),       // 2: order.service.v1.CreateOrderReq
	(*CreateOrderReply)(nil),     // 3: order.service.v1.CreateOrderReply
	(*GetOrderReq)(nil),          // 4: order.service.v1.GetOrderReq
	(*GetOrderReply)(nil),        // 5: order.service.v1.GetOrderReply
	(*UpdateOrderReq)(nil),       // 6: order.service.v1.UpdateOrderReq
	(*UpdateOrderReply)(nil),     // 7: order.service.v1.UpdateOrderReply
	(*ListOrderReply_Order)(nil), // 8: order.service.v1.ListOrderReply.Order
}
var file_order_service_v1_order_proto_depIdxs = []int32{
	8, // 0: order.service.v1.ListOrderReply.orders:type_name -> order.service.v1.ListOrderReply.Order
	0, // 1: order.service.v1.Order.ListOrder:input_type -> order.service.v1.ListOrderReq
	2, // 2: order.service.v1.Order.CreateOrder:input_type -> order.service.v1.CreateOrderReq
	4, // 3: order.service.v1.Order.GetOrder:input_type -> order.service.v1.GetOrderReq
	6, // 4: order.service.v1.Order.UpdateOrder:input_type -> order.service.v1.UpdateOrderReq
	1, // 5: order.service.v1.Order.ListOrder:output_type -> order.service.v1.ListOrderReply
	3, // 6: order.service.v1.Order.CreateOrder:output_type -> order.service.v1.CreateOrderReply
	5, // 7: order.service.v1.Order.GetOrder:output_type -> order.service.v1.GetOrderReply
	7, // 8: order.service.v1.Order.UpdateOrder:output_type -> order.service.v1.UpdateOrderReply
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_order_service_v1_order_proto_init() }
func file_order_service_v1_order_proto_init() {
	if File_order_service_v1_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_service_v1_order_proto_rawDesc), len(file_order_service_v1_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_service_v1_order_proto_goTypes,
		DependencyIndexes: file_order_service_v1_order_proto_depIdxs,
		MessageInfos:      file_order_service_v1_order_proto_msgTypes,
	}.Build()
	File_order_service_v1_order_proto = out.File
	file_order_service_v1_order_proto_goTypes = nil
	file_order_service_v1_order_proto_depIdxs = nil
}
