// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: order/service/v1/order_error.proto

package servicev1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderServiceErrorReason int32

const (
	OrderServiceErrorReason_UNKNOWN_ERROR OrderServiceErrorReason = 0
)

// Enum value maps for OrderServiceErrorReason.
var (
	OrderServiceErrorReason_name = map[int32]string{
		0: "UNKNOWN_ERROR",
	}
	OrderServiceErrorReason_value = map[string]int32{
		"UNKNOWN_ERROR": 0,
	}
)

func (x OrderServiceErrorReason) Enum() *OrderServiceErrorReason {
	p := new(OrderServiceErrorReason)
	*p = x
	return p
}

func (x OrderServiceErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderServiceErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_order_service_v1_order_error_proto_enumTypes[0].Descriptor()
}

func (OrderServiceErrorReason) Type() protoreflect.EnumType {
	return &file_order_service_v1_order_error_proto_enumTypes[0]
}

func (x OrderServiceErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderServiceErrorReason.Descriptor instead.
func (OrderServiceErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_order_service_v1_order_error_proto_rawDescGZIP(), []int{0}
}

var File_order_service_v1_order_error_proto protoreflect.FileDescriptor

const file_order_service_v1_order_error_proto_rawDesc = "" +
	"\n" +
	"\"order/service/v1/order_error.proto\x12\x10order.service.v1\x1a\x13errors/errors.proto*2\n" +
	"\x17OrderServiceErrorReason\x12\x11\n" +
	"\rUNKNOWN_ERROR\x10\x00\x1a\x04\xa0E\xf4\x03B\xcb\x01\n" +
	"\x14com.order.service.v1B\x0fOrderErrorProtoP\x01Z@tlgitea.com/pingtai/gopkg/api/_gen/go/order/service/v1;servicev1\xa2\x02\x03OSX\xaa\x02\x10Order.Service.V1\xca\x02\x10Order\\Service\\V1\xe2\x02\x1cOrder\\Service\\V1\\GPBMetadata\xea\x02\x12Order::Service::V1b\x06proto3"

var (
	file_order_service_v1_order_error_proto_rawDescOnce sync.Once
	file_order_service_v1_order_error_proto_rawDescData []byte
)

func file_order_service_v1_order_error_proto_rawDescGZIP() []byte {
	file_order_service_v1_order_error_proto_rawDescOnce.Do(func() {
		file_order_service_v1_order_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_service_v1_order_error_proto_rawDesc), len(file_order_service_v1_order_error_proto_rawDesc)))
	})
	return file_order_service_v1_order_error_proto_rawDescData
}

var file_order_service_v1_order_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_order_service_v1_order_error_proto_goTypes = []any{
	(OrderServiceErrorReason)(0), // 0: order.service.v1.OrderServiceErrorReason
}
var file_order_service_v1_order_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_order_service_v1_order_error_proto_init() }
func file_order_service_v1_order_error_proto_init() {
	if File_order_service_v1_order_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_service_v1_order_error_proto_rawDesc), len(file_order_service_v1_order_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_order_service_v1_order_error_proto_goTypes,
		DependencyIndexes: file_order_service_v1_order_error_proto_depIdxs,
		EnumInfos:         file_order_service_v1_order_error_proto_enumTypes,
	}.Build()
	File_order_service_v1_order_error_proto = out.File
	file_order_service_v1_order_error_proto_goTypes = nil
	file_order_service_v1_order_error_proto_depIdxs = nil
}
