// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: courier/job/v1/courier.proto

package jobv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_courier_job_v1_courier_proto protoreflect.FileDescriptor

const file_courier_job_v1_courier_proto_rawDesc = "" +
	"\n" +
	"\x1ccourier/job/v1/courier.proto\x12\x0ecourier.job.v1\x1a\x1cgoogle/api/annotations.proto2\t\n" +
	"\aCourierB\xb8\x01\n" +
	"\x12com.courier.job.v1B\fCourierProtoP\x01Z:tlgitea.com/pingtai/gopkg/api/_gen/go/courier/job/v1;jobv1\xa2\x02\x03CJX\xaa\x02\x0eCourier.Job.V1\xca\x02\x0eCourier\\Job\\V1\xe2\x02\x1aCourier\\Job\\V1\\GPBMetadata\xea\x02\x10Courier::Job::V1b\x06proto3"

var file_courier_job_v1_courier_proto_goTypes = []any{}
var file_courier_job_v1_courier_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_courier_job_v1_courier_proto_init() }
func file_courier_job_v1_courier_proto_init() {
	if File_courier_job_v1_courier_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_courier_job_v1_courier_proto_rawDesc), len(file_courier_job_v1_courier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_courier_job_v1_courier_proto_goTypes,
		DependencyIndexes: file_courier_job_v1_courier_proto_depIdxs,
	}.Build()
	File_courier_job_v1_courier_proto = out.File
	file_courier_job_v1_courier_proto_goTypes = nil
	file_courier_job_v1_courier_proto_depIdxs = nil
}
