// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: courier/job/v1/courier_error.proto

package jobv1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CourierJobErrorReason int32

const (
	CourierJobErrorReason_UNKNOWN_ERROR CourierJobErrorReason = 0
)

// Enum value maps for CourierJobErrorReason.
var (
	CourierJobErrorReason_name = map[int32]string{
		0: "UNKNOWN_ERROR",
	}
	CourierJobErrorReason_value = map[string]int32{
		"UNKNOWN_ERROR": 0,
	}
)

func (x CourierJobErrorReason) Enum() *CourierJobErrorReason {
	p := new(CourierJobErrorReason)
	*p = x
	return p
}

func (x CourierJobErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CourierJobErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_courier_job_v1_courier_error_proto_enumTypes[0].Descriptor()
}

func (CourierJobErrorReason) Type() protoreflect.EnumType {
	return &file_courier_job_v1_courier_error_proto_enumTypes[0]
}

func (x CourierJobErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CourierJobErrorReason.Descriptor instead.
func (CourierJobErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_courier_job_v1_courier_error_proto_rawDescGZIP(), []int{0}
}

var File_courier_job_v1_courier_error_proto protoreflect.FileDescriptor

const file_courier_job_v1_courier_error_proto_rawDesc = "" +
	"\n" +
	"\"courier/job/v1/courier_error.proto\x12\x0ecourier.job.v1\x1a\x13errors/errors.proto*0\n" +
	"\x15CourierJobErrorReason\x12\x11\n" +
	"\rUNKNOWN_ERROR\x10\x00\x1a\x04\xa0E\xf4\x03B\xbd\x01\n" +
	"\x12com.courier.job.v1B\x11CourierErrorProtoP\x01Z:tlgitea.com/pingtai/gopkg/api/_gen/go/courier/job/v1;jobv1\xa2\x02\x03CJX\xaa\x02\x0eCourier.Job.V1\xca\x02\x0eCourier\\Job\\V1\xe2\x02\x1aCourier\\Job\\V1\\GPBMetadata\xea\x02\x10Courier::Job::V1b\x06proto3"

var (
	file_courier_job_v1_courier_error_proto_rawDescOnce sync.Once
	file_courier_job_v1_courier_error_proto_rawDescData []byte
)

func file_courier_job_v1_courier_error_proto_rawDescGZIP() []byte {
	file_courier_job_v1_courier_error_proto_rawDescOnce.Do(func() {
		file_courier_job_v1_courier_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_courier_job_v1_courier_error_proto_rawDesc), len(file_courier_job_v1_courier_error_proto_rawDesc)))
	})
	return file_courier_job_v1_courier_error_proto_rawDescData
}

var file_courier_job_v1_courier_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_courier_job_v1_courier_error_proto_goTypes = []any{
	(CourierJobErrorReason)(0), // 0: courier.job.v1.CourierJobErrorReason
}
var file_courier_job_v1_courier_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_courier_job_v1_courier_error_proto_init() }
func file_courier_job_v1_courier_error_proto_init() {
	if File_courier_job_v1_courier_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_courier_job_v1_courier_error_proto_rawDesc), len(file_courier_job_v1_courier_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_courier_job_v1_courier_error_proto_goTypes,
		DependencyIndexes: file_courier_job_v1_courier_error_proto_depIdxs,
		EnumInfos:         file_courier_job_v1_courier_error_proto_enumTypes,
	}.Build()
	File_courier_job_v1_courier_error_proto = out.File
	file_courier_job_v1_courier_error_proto_goTypes = nil
	file_courier_job_v1_courier_error_proto_depIdxs = nil
}
